// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TriggeringInstruction struct {
	RefClOrdId           string   `protobuf:"bytes,1806,opt,name=RefClOrdId,json=refClordId,proto3" json:"RefClOrdId,omitempty"`
	TriggerAction        string   `protobuf:"bytes,1101,opt,name=TriggerAction,json=triggerAction,proto3" json:"TriggerAction,omitempty"`
	TriggerType          string   `protobuf:"bytes,1100,opt,name=TriggerType,json=triggerType,proto3" json:"TriggerType,omitempty"`
	TriggerScope         string   `protobuf:"bytes,1628,opt,name=TriggerScope,json=triggerScope,proto3" json:"TriggerScope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggeringInstruction) Reset()         { *m = TriggeringInstruction{} }
func (m *TriggeringInstruction) String() string { return proto.CompactTextString(m) }
func (*TriggeringInstruction) ProtoMessage()    {}
func (*TriggeringInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *TriggeringInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggeringInstruction.Unmarshal(m, b)
}
func (m *TriggeringInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggeringInstruction.Marshal(b, m, deterministic)
}
func (m *TriggeringInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggeringInstruction.Merge(m, src)
}
func (m *TriggeringInstruction) XXX_Size() int {
	return xxx_messageInfo_TriggeringInstruction.Size(m)
}
func (m *TriggeringInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggeringInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_TriggeringInstruction proto.InternalMessageInfo

func (m *TriggeringInstruction) GetRefClOrdId() string {
	if m != nil {
		return m.RefClOrdId
	}
	return ""
}

func (m *TriggeringInstruction) GetTriggerAction() string {
	if m != nil {
		return m.TriggerAction
	}
	return ""
}

func (m *TriggeringInstruction) GetTriggerType() string {
	if m != nil {
		return m.TriggerType
	}
	return ""
}

func (m *TriggeringInstruction) GetTriggerScope() string {
	if m != nil {
		return m.TriggerScope
	}
	return ""
}

type Partie struct {
	PartieId             string   `protobuf:"bytes,448,opt,name=PartieId,json=partieId,proto3" json:"PartieId,omitempty"`
	PartieRole           string   `protobuf:"bytes,45,opt,name=PartieRole,json=partieRole,proto3" json:"PartieRole,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partie) Reset()         { *m = Partie{} }
func (m *Partie) String() string { return proto.CompactTextString(m) }
func (*Partie) ProtoMessage()    {}
func (*Partie) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Partie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partie.Unmarshal(m, b)
}
func (m *Partie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partie.Marshal(b, m, deterministic)
}
func (m *Partie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partie.Merge(m, src)
}
func (m *Partie) XXX_Size() int {
	return xxx_messageInfo_Partie.Size(m)
}
func (m *Partie) XXX_DiscardUnknown() {
	xxx_messageInfo_Partie.DiscardUnknown(m)
}

var xxx_messageInfo_Partie proto.InternalMessageInfo

func (m *Partie) GetPartieId() string {
	if m != nil {
		return m.PartieId
	}
	return ""
}

func (m *Partie) GetPartieRole() string {
	if m != nil {
		return m.PartieRole
	}
	return ""
}

type SLTP struct {
	OrdType  string `protobuf:"bytes,40,opt,name=OrdType,json=ordType,proto3" json:"OrdType,omitempty"`
	Price    string `protobuf:"bytes,44,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	StopPx   string `protobuf:"bytes,99,opt,name=StopPx,json=stopPx,proto3" json:"StopPx,omitempty"`
	CapPrice string `protobuf:"bytes,1199,opt,name=CapPrice,json=capPrice,proto3" json:"CapPrice,omitempty"`
	// Trailing orders
	PegPriceType         string   `protobuf:"bytes,1094,opt,name=PegPriceType,json=pegPriceType,proto3" json:"PegPriceType,omitempty"`
	PegOffsetType        string   `protobuf:"bytes,836,opt,name=PegOffsetType,json=pegOffsetType,proto3" json:"PegOffsetType,omitempty"`
	PegOffsetValue       string   `protobuf:"bytes,211,opt,name=PegOffsetValue,json=pegOffsetValue,proto3" json:"PegOffsetValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SLTP) Reset()         { *m = SLTP{} }
func (m *SLTP) String() string { return proto.CompactTextString(m) }
func (*SLTP) ProtoMessage()    {}
func (*SLTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *SLTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SLTP.Unmarshal(m, b)
}
func (m *SLTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SLTP.Marshal(b, m, deterministic)
}
func (m *SLTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SLTP.Merge(m, src)
}
func (m *SLTP) XXX_Size() int {
	return xxx_messageInfo_SLTP.Size(m)
}
func (m *SLTP) XXX_DiscardUnknown() {
	xxx_messageInfo_SLTP.DiscardUnknown(m)
}

var xxx_messageInfo_SLTP proto.InternalMessageInfo

func (m *SLTP) GetOrdType() string {
	if m != nil {
		return m.OrdType
	}
	return ""
}

func (m *SLTP) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *SLTP) GetStopPx() string {
	if m != nil {
		return m.StopPx
	}
	return ""
}

func (m *SLTP) GetCapPrice() string {
	if m != nil {
		return m.CapPrice
	}
	return ""
}

func (m *SLTP) GetPegPriceType() string {
	if m != nil {
		return m.PegPriceType
	}
	return ""
}

func (m *SLTP) GetPegOffsetType() string {
	if m != nil {
		return m.PegOffsetType
	}
	return ""
}

func (m *SLTP) GetPegOffsetValue() string {
	if m != nil {
		return m.PegOffsetValue
	}
	return ""
}

type NewOrderSingle struct {
	MsgType string `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	// Order ID unique for Account.
	ClOrdId string `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	// Unique order ID across the exchange.
	OrderId      string `protobuf:"bytes,37,opt,name=OrderId,json=orderId,proto3" json:"OrderId,omitempty"`
	Symbol       string `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	Side         string `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	SettlType    string `protobuf:"bytes,63,opt,name=SettlType,json=settlType,proto3" json:"SettlType,omitempty"`
	TransactTime int64  `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	ListSeqNo    int32  `protobuf:"varint,67,opt,name=ListSeqNo,json=listSeqNo,proto3" json:"ListSeqNo,omitempty"`
	// Quantity of sold or bought base currency.
	// Could be change by:
	// 1. Partially order execution.
	// 2. Order modifications.
	OrderQty string `protobuf:"bytes,38,opt,name=OrderQty,json=orderQty,proto3" json:"OrderQty,omitempty"`
	OrdType  string `protobuf:"bytes,40,opt,name=OrdType,json=ordType,proto3" json:"OrdType,omitempty"`
	// For deferred orders only.
	Price    string `protobuf:"bytes,44,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	StopPx   string `protobuf:"bytes,99,opt,name=StopPx,json=stopPx,proto3" json:"StopPx,omitempty"`
	CapPrice string `protobuf:"bytes,1199,opt,name=CapPrice,json=capPrice,proto3" json:"CapPrice,omitempty"`
	// Unique client ID across echange.
	Account     uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	ExecInst    []string `protobuf:"bytes,18,rep,name=ExecInst,json=execInst,proto3" json:"ExecInst,omitempty"`
	TimeInForce string   `protobuf:"bytes,59,opt,name=TimeInForce,json=timeInForce,proto3" json:"TimeInForce,omitempty"`
	// Commission
	CommissionLevel string `protobuf:"bytes,3015,opt,name=CommissionLevel,json=commissionLevel,proto3" json:"CommissionLevel,omitempty"`
	// Trailing orders
	PegPriceType   string `protobuf:"bytes,1094,opt,name=PegPriceType,json=pegPriceType,proto3" json:"PegPriceType,omitempty"`
	PegOffsetType  string `protobuf:"bytes,836,opt,name=PegOffsetType,json=pegOffsetType,proto3" json:"PegOffsetType,omitempty"`
	PegOffsetValue string `protobuf:"bytes,211,opt,name=PegOffsetValue,json=pegOffsetValue,proto3" json:"PegOffsetValue,omitempty"`
	// Triggers
	TriggeringInstructions []*TriggeringInstruction `protobuf:"bytes,1114,rep,name=TriggeringInstructions,json=triggeringInstructions,proto3" json:"TriggeringInstructions,omitempty"`
	// Deriative positions
	PositionId     uint64 `protobuf:"varint,2618,opt,name=PositionId,json=positionId,proto3" json:"PositionId,omitempty"`
	PositionEffect string `protobuf:"bytes,77,opt,name=PositionEffect,json=positionEffect,proto3" json:"PositionEffect,omitempty"`
	// Derivative SLTP
	SLTP                 []*SLTP  `protobuf:"bytes,5000,rep,name=SLTP,json=sltp,proto3" json:"SLTP,omitempty"`
	Text                 string   `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderSingle) Reset()         { *m = NewOrderSingle{} }
func (m *NewOrderSingle) String() string { return proto.CompactTextString(m) }
func (*NewOrderSingle) ProtoMessage()    {}
func (*NewOrderSingle) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *NewOrderSingle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderSingle.Unmarshal(m, b)
}
func (m *NewOrderSingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderSingle.Marshal(b, m, deterministic)
}
func (m *NewOrderSingle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderSingle.Merge(m, src)
}
func (m *NewOrderSingle) XXX_Size() int {
	return xxx_messageInfo_NewOrderSingle.Size(m)
}
func (m *NewOrderSingle) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderSingle.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderSingle proto.InternalMessageInfo

func (m *NewOrderSingle) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *NewOrderSingle) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *NewOrderSingle) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *NewOrderSingle) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *NewOrderSingle) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *NewOrderSingle) GetSettlType() string {
	if m != nil {
		return m.SettlType
	}
	return ""
}

func (m *NewOrderSingle) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *NewOrderSingle) GetListSeqNo() int32 {
	if m != nil {
		return m.ListSeqNo
	}
	return 0
}

func (m *NewOrderSingle) GetOrderQty() string {
	if m != nil {
		return m.OrderQty
	}
	return ""
}

func (m *NewOrderSingle) GetOrdType() string {
	if m != nil {
		return m.OrdType
	}
	return ""
}

func (m *NewOrderSingle) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *NewOrderSingle) GetStopPx() string {
	if m != nil {
		return m.StopPx
	}
	return ""
}

func (m *NewOrderSingle) GetCapPrice() string {
	if m != nil {
		return m.CapPrice
	}
	return ""
}

func (m *NewOrderSingle) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *NewOrderSingle) GetExecInst() []string {
	if m != nil {
		return m.ExecInst
	}
	return nil
}

func (m *NewOrderSingle) GetTimeInForce() string {
	if m != nil {
		return m.TimeInForce
	}
	return ""
}

func (m *NewOrderSingle) GetCommissionLevel() string {
	if m != nil {
		return m.CommissionLevel
	}
	return ""
}

func (m *NewOrderSingle) GetPegPriceType() string {
	if m != nil {
		return m.PegPriceType
	}
	return ""
}

func (m *NewOrderSingle) GetPegOffsetType() string {
	if m != nil {
		return m.PegOffsetType
	}
	return ""
}

func (m *NewOrderSingle) GetPegOffsetValue() string {
	if m != nil {
		return m.PegOffsetValue
	}
	return ""
}

func (m *NewOrderSingle) GetTriggeringInstructions() []*TriggeringInstruction {
	if m != nil {
		return m.TriggeringInstructions
	}
	return nil
}

func (m *NewOrderSingle) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *NewOrderSingle) GetPositionEffect() string {
	if m != nil {
		return m.PositionEffect
	}
	return ""
}

func (m *NewOrderSingle) GetSLTP() []*SLTP {
	if m != nil {
		return m.SLTP
	}
	return nil
}

func (m *NewOrderSingle) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ExecutionReport struct {
	MsgType string `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	// Finance account. Unique client ID across exchange.
	Account uint64 `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	// Client order identificator.
	ClOrdId     string `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	OrigClOrdId string `protobuf:"bytes,41,opt,name=OrigClOrdId,json=origClOrdId,proto3" json:"OrigClOrdId,omitempty"`
	OrderId     string `protobuf:"bytes,37,opt,name=OrderId,json=orderId,proto3" json:"OrderId,omitempty"`
	ListId      string `protobuf:"bytes,66,opt,name=ListId,json=listId,proto3" json:"ListId,omitempty"`
	// Trade instrument name.
	Symbol      string   `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	OrdType     string   `protobuf:"bytes,40,opt,name=OrdType,json=ordType,proto3" json:"OrdType,omitempty"`
	Price       string   `protobuf:"bytes,44,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	StopPx      string   `protobuf:"bytes,99,opt,name=StopPx,json=stopPx,proto3" json:"StopPx,omitempty"`
	ExecInst    []string `protobuf:"bytes,18,rep,name=ExecInst,json=execInst,proto3" json:"ExecInst,omitempty"`
	TimeInForce string   `protobuf:"bytes,59,opt,name=TimeInForce,json=timeInForce,proto3" json:"TimeInForce,omitempty"`
	// Moment(timestamp) of transaction execution.
	TransactTime          int64  `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	ExecId                string `protobuf:"bytes,17,opt,name=ExecId,json=execId,proto3" json:"ExecId,omitempty"`
	ExecType              string `protobuf:"bytes,150,opt,name=ExecType,json=execType,proto3" json:"ExecType,omitempty"`
	ExecRestatementReason string `protobuf:"bytes,378,opt,name=ExecRestatementReason,json=execRestatementReason,proto3" json:"ExecRestatementReason,omitempty"`
	// Trade identifier
	TradeId string `protobuf:"bytes,1003,opt,name=TradeId,json=tradeId,proto3" json:"TradeId,omitempty"`
	// Current order status.
	OrdStatus string `protobuf:"bytes,39,opt,name=OrdStatus,json=ordStatus,proto3" json:"OrdStatus,omitempty"`
	// Rejection reason.
	OrdRejReason string `protobuf:"bytes,103,opt,name=OrdRejReason,json=ordRejReason,proto3" json:"OrdRejReason,omitempty"`
	// Trade side, could be Buy or Sell.
	Side string `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	// Current OrderQty value. Could be changed by trader.
	OrderQty string `protobuf:"bytes,38,opt,name=OrderQty,json=orderQty,proto3" json:"OrderQty,omitempty"`
	// Quantity which is leaved after last execution.
	LeavesQty string `protobuf:"bytes,151,opt,name=LeavesQty,json=leavesQty,proto3" json:"LeavesQty,omitempty"`
	// Cummulative quantity value of executed part of order.
	CumQty string `protobuf:"bytes,14,opt,name=CumQty,json=cumQty,proto3" json:"CumQty,omitempty"`
	// Quantity closed by last execution.
	LastQty string `protobuf:"bytes,32,opt,name=LastQty,json=lastQty,proto3" json:"LastQty,omitempty"`
	// Stop order CapPrice
	CapPrice string `protobuf:"bytes,1199,opt,name=CapPrice,json=capPrice,proto3" json:"CapPrice,omitempty"`
	// Execution price.
	LastPx               string `protobuf:"bytes,31,opt,name=LastPx,json=lastPx,proto3" json:"LastPx,omitempty"`
	AvgPx                string `protobuf:"bytes,6,opt,name=AvgPx,json=avgPx,proto3" json:"AvgPx,omitempty"`
	CalculatedCcyLastQty string `protobuf:"bytes,1056,opt,name=CalculatedCcyLastQty,json=calculatedCcyLastQty,proto3" json:"CalculatedCcyLastQty,omitempty"`
	Currency             string `protobuf:"bytes,15,opt,name=Currency,json=currency,proto3" json:"Currency,omitempty"`
	SettlCurrency        string `protobuf:"bytes,120,opt,name=SettlCurrency,json=settlCurrency,proto3" json:"SettlCurrency,omitempty"`
	SettlType            string `protobuf:"bytes,63,opt,name=SettlType,json=settlType,proto3" json:"SettlType,omitempty"`
	NetMoney             string `protobuf:"bytes,118,opt,name=NetMoney,json=netMoney,proto3" json:"NetMoney,omitempty"`
	// Commission
	LastLiquidityInd string `protobuf:"bytes,851,opt,name=LastLiquidityInd,json=lastLiquidityInd,proto3" json:"LastLiquidityInd,omitempty"`
	Commission       string `protobuf:"bytes,12,opt,name=Commission,json=commission,proto3" json:"Commission,omitempty"`
	CommRate         string `protobuf:"bytes,1233,opt,name=CommRate,json=commRate,proto3" json:"CommRate,omitempty"`
	CommCurrency     string `protobuf:"bytes,479,opt,name=CommCurrency,json=commCurrency,proto3" json:"CommCurrency,omitempty"`
	// Rejection detailed description.
	RejectText string `protobuf:"bytes,1328,opt,name=RejectText,json=rejectText,proto3" json:"RejectText,omitempty"`
	// Trailings
	PegPriceType   string `protobuf:"bytes,1094,opt,name=PegPriceType,json=pegPriceType,proto3" json:"PegPriceType,omitempty"`
	PegOffsetType  string `protobuf:"bytes,836,opt,name=PegOffsetType,json=pegOffsetType,proto3" json:"PegOffsetType,omitempty"`
	PegOffsetValue string `protobuf:"bytes,211,opt,name=PegOffsetValue,json=pegOffsetValue,proto3" json:"PegOffsetValue,omitempty"`
	// Position
	PositionId     uint64 `protobuf:"varint,2618,opt,name=PositionId,json=positionId,proto3" json:"PositionId,omitempty"`
	PositionEffect string `protobuf:"bytes,77,opt,name=PositionEffect,json=positionEffect,proto3" json:"PositionEffect,omitempty"`
	// Margin
	MarginAmt     string `protobuf:"bytes,1645,opt,name=MarginAmt,json=marginAmt,proto3" json:"MarginAmt,omitempty"`
	MarginAmtType string `protobuf:"bytes,1644,opt,name=MarginAmtType,json=marginAmtType,proto3" json:"MarginAmtType,omitempty"`
	MarginAmtCcy  string `protobuf:"bytes,1646,opt,name=MarginAmtCcy,json=marginAmtCcy,proto3" json:"MarginAmtCcy,omitempty"`
	// Derivative SLTP
	SLTP                 []*SLTP  `protobuf:"bytes,5000,rep,name=SLTP,json=sltp,proto3" json:"SLTP,omitempty"`
	Text                 string   `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutionReport) Reset()         { *m = ExecutionReport{} }
func (m *ExecutionReport) String() string { return proto.CompactTextString(m) }
func (*ExecutionReport) ProtoMessage()    {}
func (*ExecutionReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *ExecutionReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionReport.Unmarshal(m, b)
}
func (m *ExecutionReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionReport.Marshal(b, m, deterministic)
}
func (m *ExecutionReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionReport.Merge(m, src)
}
func (m *ExecutionReport) XXX_Size() int {
	return xxx_messageInfo_ExecutionReport.Size(m)
}
func (m *ExecutionReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionReport.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionReport proto.InternalMessageInfo

func (m *ExecutionReport) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *ExecutionReport) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *ExecutionReport) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *ExecutionReport) GetOrigClOrdId() string {
	if m != nil {
		return m.OrigClOrdId
	}
	return ""
}

func (m *ExecutionReport) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ExecutionReport) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func (m *ExecutionReport) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ExecutionReport) GetOrdType() string {
	if m != nil {
		return m.OrdType
	}
	return ""
}

func (m *ExecutionReport) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *ExecutionReport) GetStopPx() string {
	if m != nil {
		return m.StopPx
	}
	return ""
}

func (m *ExecutionReport) GetExecInst() []string {
	if m != nil {
		return m.ExecInst
	}
	return nil
}

func (m *ExecutionReport) GetTimeInForce() string {
	if m != nil {
		return m.TimeInForce
	}
	return ""
}

func (m *ExecutionReport) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *ExecutionReport) GetExecId() string {
	if m != nil {
		return m.ExecId
	}
	return ""
}

func (m *ExecutionReport) GetExecType() string {
	if m != nil {
		return m.ExecType
	}
	return ""
}

func (m *ExecutionReport) GetExecRestatementReason() string {
	if m != nil {
		return m.ExecRestatementReason
	}
	return ""
}

func (m *ExecutionReport) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *ExecutionReport) GetOrdStatus() string {
	if m != nil {
		return m.OrdStatus
	}
	return ""
}

func (m *ExecutionReport) GetOrdRejReason() string {
	if m != nil {
		return m.OrdRejReason
	}
	return ""
}

func (m *ExecutionReport) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *ExecutionReport) GetOrderQty() string {
	if m != nil {
		return m.OrderQty
	}
	return ""
}

func (m *ExecutionReport) GetLeavesQty() string {
	if m != nil {
		return m.LeavesQty
	}
	return ""
}

func (m *ExecutionReport) GetCumQty() string {
	if m != nil {
		return m.CumQty
	}
	return ""
}

func (m *ExecutionReport) GetLastQty() string {
	if m != nil {
		return m.LastQty
	}
	return ""
}

func (m *ExecutionReport) GetCapPrice() string {
	if m != nil {
		return m.CapPrice
	}
	return ""
}

func (m *ExecutionReport) GetLastPx() string {
	if m != nil {
		return m.LastPx
	}
	return ""
}

func (m *ExecutionReport) GetAvgPx() string {
	if m != nil {
		return m.AvgPx
	}
	return ""
}

func (m *ExecutionReport) GetCalculatedCcyLastQty() string {
	if m != nil {
		return m.CalculatedCcyLastQty
	}
	return ""
}

func (m *ExecutionReport) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *ExecutionReport) GetSettlCurrency() string {
	if m != nil {
		return m.SettlCurrency
	}
	return ""
}

func (m *ExecutionReport) GetSettlType() string {
	if m != nil {
		return m.SettlType
	}
	return ""
}

func (m *ExecutionReport) GetNetMoney() string {
	if m != nil {
		return m.NetMoney
	}
	return ""
}

func (m *ExecutionReport) GetLastLiquidityInd() string {
	if m != nil {
		return m.LastLiquidityInd
	}
	return ""
}

func (m *ExecutionReport) GetCommission() string {
	if m != nil {
		return m.Commission
	}
	return ""
}

func (m *ExecutionReport) GetCommRate() string {
	if m != nil {
		return m.CommRate
	}
	return ""
}

func (m *ExecutionReport) GetCommCurrency() string {
	if m != nil {
		return m.CommCurrency
	}
	return ""
}

func (m *ExecutionReport) GetRejectText() string {
	if m != nil {
		return m.RejectText
	}
	return ""
}

func (m *ExecutionReport) GetPegPriceType() string {
	if m != nil {
		return m.PegPriceType
	}
	return ""
}

func (m *ExecutionReport) GetPegOffsetType() string {
	if m != nil {
		return m.PegOffsetType
	}
	return ""
}

func (m *ExecutionReport) GetPegOffsetValue() string {
	if m != nil {
		return m.PegOffsetValue
	}
	return ""
}

func (m *ExecutionReport) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *ExecutionReport) GetPositionEffect() string {
	if m != nil {
		return m.PositionEffect
	}
	return ""
}

func (m *ExecutionReport) GetMarginAmt() string {
	if m != nil {
		return m.MarginAmt
	}
	return ""
}

func (m *ExecutionReport) GetMarginAmtType() string {
	if m != nil {
		return m.MarginAmtType
	}
	return ""
}

func (m *ExecutionReport) GetMarginAmtCcy() string {
	if m != nil {
		return m.MarginAmtCcy
	}
	return ""
}

func (m *ExecutionReport) GetSLTP() []*SLTP {
	if m != nil {
		return m.SLTP
	}
	return nil
}

func (m *ExecutionReport) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type OrderCancelRequest struct {
	MsgType string `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	// Request ID unique for Account.
	ClOrdId string `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	// Client Order ID (ClOrdId) of order to cancel
	OrigClOrdId string `protobuf:"bytes,41,opt,name=OrigClOrdId,json=origClOrdId,proto3" json:"OrigClOrdId,omitempty"`
	// Unique order ID across the exchange.
	OrderId      string `protobuf:"bytes,37,opt,name=OrderId,json=orderId,proto3" json:"OrderId,omitempty"`
	Symbol       string `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	Side         string `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	TransactTime int64  `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	// Unique client ID across exchange.
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancelRequest) Reset()         { *m = OrderCancelRequest{} }
func (m *OrderCancelRequest) String() string { return proto.CompactTextString(m) }
func (*OrderCancelRequest) ProtoMessage()    {}
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *OrderCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancelRequest.Unmarshal(m, b)
}
func (m *OrderCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancelRequest.Marshal(b, m, deterministic)
}
func (m *OrderCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancelRequest.Merge(m, src)
}
func (m *OrderCancelRequest) XXX_Size() int {
	return xxx_messageInfo_OrderCancelRequest.Size(m)
}
func (m *OrderCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancelRequest proto.InternalMessageInfo

func (m *OrderCancelRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderCancelRequest) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *OrderCancelRequest) GetOrigClOrdId() string {
	if m != nil {
		return m.OrigClOrdId
	}
	return ""
}

func (m *OrderCancelRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCancelRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderCancelRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderCancelRequest) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *OrderCancelRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type OrderCancelReject struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	Symbol               string   `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	ClOrdId              string   `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	OrigClOrdId          string   `protobuf:"bytes,41,opt,name=OrigClOrdId,json=origClOrdId,proto3" json:"OrigClOrdId,omitempty"`
	OrderId              string   `protobuf:"bytes,37,opt,name=OrderId,json=orderId,proto3" json:"OrderId,omitempty"`
	OrdStatus            string   `protobuf:"bytes,39,opt,name=OrdStatus,json=ordStatus,proto3" json:"OrdStatus,omitempty"`
	CxlRejResponseTo     string   `protobuf:"bytes,434,opt,name=CxlRejResponseTo,json=cxlRejResponseTo,proto3" json:"CxlRejResponseTo,omitempty"`
	CxlRejReason         string   `protobuf:"bytes,102,opt,name=CxlRejReason,json=cxlRejReason,proto3" json:"CxlRejReason,omitempty"`
	RejectText           string   `protobuf:"bytes,1328,opt,name=RejectText,json=rejectText,proto3" json:"RejectText,omitempty"`
	TransactTime         int64    `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancelReject) Reset()         { *m = OrderCancelReject{} }
func (m *OrderCancelReject) String() string { return proto.CompactTextString(m) }
func (*OrderCancelReject) ProtoMessage()    {}
func (*OrderCancelReject) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *OrderCancelReject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancelReject.Unmarshal(m, b)
}
func (m *OrderCancelReject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancelReject.Marshal(b, m, deterministic)
}
func (m *OrderCancelReject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancelReject.Merge(m, src)
}
func (m *OrderCancelReject) XXX_Size() int {
	return xxx_messageInfo_OrderCancelReject.Size(m)
}
func (m *OrderCancelReject) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancelReject.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancelReject proto.InternalMessageInfo

func (m *OrderCancelReject) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderCancelReject) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *OrderCancelReject) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderCancelReject) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *OrderCancelReject) GetOrigClOrdId() string {
	if m != nil {
		return m.OrigClOrdId
	}
	return ""
}

func (m *OrderCancelReject) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCancelReject) GetOrdStatus() string {
	if m != nil {
		return m.OrdStatus
	}
	return ""
}

func (m *OrderCancelReject) GetCxlRejResponseTo() string {
	if m != nil {
		return m.CxlRejResponseTo
	}
	return ""
}

func (m *OrderCancelReject) GetCxlRejReason() string {
	if m != nil {
		return m.CxlRejReason
	}
	return ""
}

func (m *OrderCancelReject) GetRejectText() string {
	if m != nil {
		return m.RejectText
	}
	return ""
}

func (m *OrderCancelReject) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

type OrderMassCancelRequest struct {
	MsgType               string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	ClOrdId               string   `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	MassCancelRequestType string   `protobuf:"bytes,530,opt,name=MassCancelRequestType,json=massCancelRequestType,proto3" json:"MassCancelRequestType,omitempty"`
	Symbol                string   `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	Side                  string   `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	PositionEffect        string   `protobuf:"bytes,77,opt,name=PositionEffect,json=positionEffect,proto3" json:"PositionEffect,omitempty"`
	Account               uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *OrderMassCancelRequest) Reset()         { *m = OrderMassCancelRequest{} }
func (m *OrderMassCancelRequest) String() string { return proto.CompactTextString(m) }
func (*OrderMassCancelRequest) ProtoMessage()    {}
func (*OrderMassCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *OrderMassCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMassCancelRequest.Unmarshal(m, b)
}
func (m *OrderMassCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMassCancelRequest.Marshal(b, m, deterministic)
}
func (m *OrderMassCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMassCancelRequest.Merge(m, src)
}
func (m *OrderMassCancelRequest) XXX_Size() int {
	return xxx_messageInfo_OrderMassCancelRequest.Size(m)
}
func (m *OrderMassCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMassCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMassCancelRequest proto.InternalMessageInfo

func (m *OrderMassCancelRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderMassCancelRequest) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *OrderMassCancelRequest) GetMassCancelRequestType() string {
	if m != nil {
		return m.MassCancelRequestType
	}
	return ""
}

func (m *OrderMassCancelRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderMassCancelRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderMassCancelRequest) GetPositionEffect() string {
	if m != nil {
		return m.PositionEffect
	}
	return ""
}

func (m *OrderMassCancelRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type OrderMassCancelReport struct {
	MsgType                string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	ClOrdId                string   `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	MassActionReportID     string   `protobuf:"bytes,1369,opt,name=MassActionReportID,json=massActionReportID,proto3" json:"MassActionReportID,omitempty"`
	MassCancelResponse     string   `protobuf:"bytes,531,opt,name=MassCancelResponse,json=massCancelResponse,proto3" json:"MassCancelResponse,omitempty"`
	MassCancelRejectReason string   `protobuf:"bytes,532,opt,name=MassCancelRejectReason,json=massCancelRejectReason,proto3" json:"MassCancelRejectReason,omitempty"`
	RejectText             string   `protobuf:"bytes,1328,opt,name=RejectText,json=rejectText,proto3" json:"RejectText,omitempty"`
	Symbol                 string   `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	Side                   string   `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	TransactTime           int64    `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	TotalAffectedOrders    int64    `protobuf:"varint,533,opt,name=TotalAffectedOrders,json=totalAffectedOrders,proto3" json:"TotalAffectedOrders,omitempty"`
	Account                uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *OrderMassCancelReport) Reset()         { *m = OrderMassCancelReport{} }
func (m *OrderMassCancelReport) String() string { return proto.CompactTextString(m) }
func (*OrderMassCancelReport) ProtoMessage()    {}
func (*OrderMassCancelReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *OrderMassCancelReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMassCancelReport.Unmarshal(m, b)
}
func (m *OrderMassCancelReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMassCancelReport.Marshal(b, m, deterministic)
}
func (m *OrderMassCancelReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMassCancelReport.Merge(m, src)
}
func (m *OrderMassCancelReport) XXX_Size() int {
	return xxx_messageInfo_OrderMassCancelReport.Size(m)
}
func (m *OrderMassCancelReport) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMassCancelReport.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMassCancelReport proto.InternalMessageInfo

func (m *OrderMassCancelReport) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderMassCancelReport) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *OrderMassCancelReport) GetMassActionReportID() string {
	if m != nil {
		return m.MassActionReportID
	}
	return ""
}

func (m *OrderMassCancelReport) GetMassCancelResponse() string {
	if m != nil {
		return m.MassCancelResponse
	}
	return ""
}

func (m *OrderMassCancelReport) GetMassCancelRejectReason() string {
	if m != nil {
		return m.MassCancelRejectReason
	}
	return ""
}

func (m *OrderMassCancelReport) GetRejectText() string {
	if m != nil {
		return m.RejectText
	}
	return ""
}

func (m *OrderMassCancelReport) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderMassCancelReport) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderMassCancelReport) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *OrderMassCancelReport) GetTotalAffectedOrders() int64 {
	if m != nil {
		return m.TotalAffectedOrders
	}
	return 0
}

func (m *OrderMassCancelReport) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type OrderStatusRequest struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	MassStatusReqId      string   `protobuf:"bytes,584,opt,name=MassStatusReqId,json=massStatusReqId,proto3" json:"MassStatusReqId,omitempty"`
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusRequest) Reset()         { *m = OrderStatusRequest{} }
func (m *OrderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*OrderStatusRequest) ProtoMessage()    {}
func (*OrderStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *OrderStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusRequest.Unmarshal(m, b)
}
func (m *OrderStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusRequest.Marshal(b, m, deterministic)
}
func (m *OrderStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusRequest.Merge(m, src)
}
func (m *OrderStatusRequest) XXX_Size() int {
	return xxx_messageInfo_OrderStatusRequest.Size(m)
}
func (m *OrderStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusRequest proto.InternalMessageInfo

func (m *OrderStatusRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderStatusRequest) GetMassStatusReqId() string {
	if m != nil {
		return m.MassStatusReqId
	}
	return ""
}

func (m *OrderStatusRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type Reject struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	RejectReason         string   `protobuf:"bytes,380,opt,name=RejectReason,json=rejectReason,proto3" json:"RejectReason,omitempty"`
	Text                 string   `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reject) Reset()         { *m = Reject{} }
func (m *Reject) String() string { return proto.CompactTextString(m) }
func (*Reject) ProtoMessage()    {}
func (*Reject) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *Reject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reject.Unmarshal(m, b)
}
func (m *Reject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reject.Marshal(b, m, deterministic)
}
func (m *Reject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reject.Merge(m, src)
}
func (m *Reject) XXX_Size() int {
	return xxx_messageInfo_Reject.Size(m)
}
func (m *Reject) XXX_DiscardUnknown() {
	xxx_messageInfo_Reject.DiscardUnknown(m)
}

var xxx_messageInfo_Reject proto.InternalMessageInfo

func (m *Reject) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *Reject) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

func (m *Reject) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type OrderMassStatusResponse struct {
	MsgType              string             `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	MassStatusReqId      string             `protobuf:"bytes,584,opt,name=MassStatusReqId,json=massStatusReqId,proto3" json:"MassStatusReqId,omitempty"`
	Account              uint64             `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	Orders               []*ExecutionReport `protobuf:"bytes,1268,rep,name=Orders,json=orders,proto3" json:"Orders,omitempty"`
	Fills                []*ExecutionReport `protobuf:"bytes,1269,rep,name=Fills,json=fills,proto3" json:"Fills,omitempty"`
	RejectReason         string             `protobuf:"bytes,380,opt,name=RejectReason,json=rejectReason,proto3" json:"RejectReason,omitempty"`
	Text                 string             `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OrderMassStatusResponse) Reset()         { *m = OrderMassStatusResponse{} }
func (m *OrderMassStatusResponse) String() string { return proto.CompactTextString(m) }
func (*OrderMassStatusResponse) ProtoMessage()    {}
func (*OrderMassStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *OrderMassStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMassStatusResponse.Unmarshal(m, b)
}
func (m *OrderMassStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMassStatusResponse.Marshal(b, m, deterministic)
}
func (m *OrderMassStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMassStatusResponse.Merge(m, src)
}
func (m *OrderMassStatusResponse) XXX_Size() int {
	return xxx_messageInfo_OrderMassStatusResponse.Size(m)
}
func (m *OrderMassStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMassStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMassStatusResponse proto.InternalMessageInfo

func (m *OrderMassStatusResponse) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderMassStatusResponse) GetMassStatusReqId() string {
	if m != nil {
		return m.MassStatusReqId
	}
	return ""
}

func (m *OrderMassStatusResponse) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *OrderMassStatusResponse) GetOrders() []*ExecutionReport {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *OrderMassStatusResponse) GetFills() []*ExecutionReport {
	if m != nil {
		return m.Fills
	}
	return nil
}

func (m *OrderMassStatusResponse) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

func (m *OrderMassStatusResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type OrderCancelReplaceRequest struct {
	MsgType string `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	// Request ID unique for Account.
	ClOrdId string `protobuf:"bytes,11,opt,name=ClOrdId,json=clOrdId,proto3" json:"ClOrdId,omitempty"`
	// Client Order ID (ClOrdId) of order to modify
	OrigClOrdId string `protobuf:"bytes,41,opt,name=OrigClOrdId,json=origClOrdId,proto3" json:"OrigClOrdId,omitempty"`
	// Unique order ID across the exchange.
	OrderId      string `protobuf:"bytes,37,opt,name=OrderId,json=orderId,proto3" json:"OrderId,omitempty"`
	Symbol       string `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	Side         string `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	TransactTime int64  `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	// Unique client ID across exchange.
	Account uint64 `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	// New ExecInst
	ExecInst []string `protobuf:"bytes,18,rep,name=ExecInst,json=execInst,proto3" json:"ExecInst,omitempty"`
	// New fields
	OrderQty       string `protobuf:"bytes,38,opt,name=OrderQty,json=orderQty,proto3" json:"OrderQty,omitempty"`
	Price          string `protobuf:"bytes,44,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	StopPx         string `protobuf:"bytes,99,opt,name=StopPx,json=stopPx,proto3" json:"StopPx,omitempty"`
	CapPrice       string `protobuf:"bytes,1199,opt,name=CapPrice,json=capPrice,proto3" json:"CapPrice,omitempty"`
	PegPriceType   string `protobuf:"bytes,1094,opt,name=PegPriceType,json=pegPriceType,proto3" json:"PegPriceType,omitempty"`
	PegOffsetType  string `protobuf:"bytes,836,opt,name=PegOffsetType,json=pegOffsetType,proto3" json:"PegOffsetType,omitempty"`
	PegOffsetValue string `protobuf:"bytes,211,opt,name=PegOffsetValue,json=pegOffsetValue,proto3" json:"PegOffsetValue,omitempty"`
	// Derivative SLTP
	SLTP                 []*SLTP  `protobuf:"bytes,5000,rep,name=SLTP,json=sltp,proto3" json:"SLTP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancelReplaceRequest) Reset()         { *m = OrderCancelReplaceRequest{} }
func (m *OrderCancelReplaceRequest) String() string { return proto.CompactTextString(m) }
func (*OrderCancelReplaceRequest) ProtoMessage()    {}
func (*OrderCancelReplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *OrderCancelReplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancelReplaceRequest.Unmarshal(m, b)
}
func (m *OrderCancelReplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancelReplaceRequest.Marshal(b, m, deterministic)
}
func (m *OrderCancelReplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancelReplaceRequest.Merge(m, src)
}
func (m *OrderCancelReplaceRequest) XXX_Size() int {
	return xxx_messageInfo_OrderCancelReplaceRequest.Size(m)
}
func (m *OrderCancelReplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancelReplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancelReplaceRequest proto.InternalMessageInfo

func (m *OrderCancelReplaceRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetClOrdId() string {
	if m != nil {
		return m.ClOrdId
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetOrigClOrdId() string {
	if m != nil {
		return m.OrigClOrdId
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *OrderCancelReplaceRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *OrderCancelReplaceRequest) GetExecInst() []string {
	if m != nil {
		return m.ExecInst
	}
	return nil
}

func (m *OrderCancelReplaceRequest) GetOrderQty() string {
	if m != nil {
		return m.OrderQty
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetStopPx() string {
	if m != nil {
		return m.StopPx
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetCapPrice() string {
	if m != nil {
		return m.CapPrice
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetPegPriceType() string {
	if m != nil {
		return m.PegPriceType
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetPegOffsetType() string {
	if m != nil {
		return m.PegOffsetType
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetPegOffsetValue() string {
	if m != nil {
		return m.PegOffsetValue
	}
	return ""
}

func (m *OrderCancelReplaceRequest) GetSLTP() []*SLTP {
	if m != nil {
		return m.SLTP
	}
	return nil
}

type NewOrderList struct {
	MsgType string `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	// List ID unique for Account.
	ListId          string            `protobuf:"bytes,66,opt,name=ListId,json=listId,proto3" json:"ListId,omitempty"`
	BidType         string            `protobuf:"bytes,394,opt,name=BidType,json=bidType,proto3" json:"BidType,omitempty"`
	TotNoOrders     int32             `protobuf:"varint,68,opt,name=TotNoOrders,json=totNoOrders,proto3" json:"TotNoOrders,omitempty"`
	ContingencyType string            `protobuf:"bytes,1385,opt,name=ContingencyType,json=contingencyType,proto3" json:"ContingencyType,omitempty"`
	ListOrdGrp      []*NewOrderSingle `protobuf:"bytes,73,rep,name=ListOrdGrp,json=listOrdGrp,proto3" json:"ListOrdGrp,omitempty"`
	NestedListGrp   []*NewOrderList   `protobuf:"bytes,1773,rep,name=NestedListGrp,json=nestedListGrp,proto3" json:"NestedListGrp,omitempty"`
	Symbol          string            `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	TransactTime    int64             `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	// Unique client ID across echange.
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderList) Reset()         { *m = NewOrderList{} }
func (m *NewOrderList) String() string { return proto.CompactTextString(m) }
func (*NewOrderList) ProtoMessage()    {}
func (*NewOrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *NewOrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderList.Unmarshal(m, b)
}
func (m *NewOrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderList.Marshal(b, m, deterministic)
}
func (m *NewOrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderList.Merge(m, src)
}
func (m *NewOrderList) XXX_Size() int {
	return xxx_messageInfo_NewOrderList.Size(m)
}
func (m *NewOrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderList.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderList proto.InternalMessageInfo

func (m *NewOrderList) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *NewOrderList) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func (m *NewOrderList) GetBidType() string {
	if m != nil {
		return m.BidType
	}
	return ""
}

func (m *NewOrderList) GetTotNoOrders() int32 {
	if m != nil {
		return m.TotNoOrders
	}
	return 0
}

func (m *NewOrderList) GetContingencyType() string {
	if m != nil {
		return m.ContingencyType
	}
	return ""
}

func (m *NewOrderList) GetListOrdGrp() []*NewOrderSingle {
	if m != nil {
		return m.ListOrdGrp
	}
	return nil
}

func (m *NewOrderList) GetNestedListGrp() []*NewOrderList {
	if m != nil {
		return m.NestedListGrp
	}
	return nil
}

func (m *NewOrderList) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *NewOrderList) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *NewOrderList) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type OrderListAction struct {
	ContingencyType      string   `protobuf:"bytes,1385,opt,name=ContingencyType,json=contingencyType,proto3" json:"ContingencyType,omitempty"`
	OrderId              []string `protobuf:"bytes,37,rep,name=OrderId,json=orderId,proto3" json:"OrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderListAction) Reset()         { *m = OrderListAction{} }
func (m *OrderListAction) String() string { return proto.CompactTextString(m) }
func (*OrderListAction) ProtoMessage()    {}
func (*OrderListAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{14}
}

func (m *OrderListAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListAction.Unmarshal(m, b)
}
func (m *OrderListAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListAction.Marshal(b, m, deterministic)
}
func (m *OrderListAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListAction.Merge(m, src)
}
func (m *OrderListAction) XXX_Size() int {
	return xxx_messageInfo_OrderListAction.Size(m)
}
func (m *OrderListAction) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListAction.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListAction proto.InternalMessageInfo

func (m *OrderListAction) GetContingencyType() string {
	if m != nil {
		return m.ContingencyType
	}
	return ""
}

func (m *OrderListAction) GetOrderId() []string {
	if m != nil {
		return m.OrderId
	}
	return nil
}

type ListStatus struct {
	MsgType string `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	// Finance account. Unique client ID across exchange.
	Account uint64 `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	// List ID unique for Account.
	ListId string `protobuf:"bytes,66,opt,name=ListId,json=listId,proto3" json:"ListId,omitempty"`
	// Trade instrument name.
	Symbol           string           `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	ListStatusType   string           `protobuf:"bytes,429,opt,name=ListStatusType,json=listStatusType,proto3" json:"ListStatusType,omitempty"`
	ListOrderStatus  string           `protobuf:"bytes,431,opt,name=ListOrderStatus,json=listOrderStatus,proto3" json:"ListOrderStatus,omitempty"`
	ContingencyType  string           `protobuf:"bytes,1385,opt,name=ContingencyType,json=contingencyType,proto3" json:"ContingencyType,omitempty"`
	ListRejectReason string           `protobuf:"bytes,1386,opt,name=ListRejectReason,json=listRejectReason,proto3" json:"ListRejectReason,omitempty"`
	ListRejectOrder  *ExecutionReport `protobuf:"bytes,1387,opt,name=ListRejectOrder,json=listRejectOrder,proto3" json:"ListRejectOrder,omitempty"`
	// Moment(timestamp) of transaction execution.
	TransactTime         int64    `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	ListStatusText       string   `protobuf:"bytes,444,opt,name=ListStatusText,json=listStatusText,proto3" json:"ListStatusText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStatus) Reset()         { *m = ListStatus{} }
func (m *ListStatus) String() string { return proto.CompactTextString(m) }
func (*ListStatus) ProtoMessage()    {}
func (*ListStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{15}
}

func (m *ListStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStatus.Unmarshal(m, b)
}
func (m *ListStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStatus.Marshal(b, m, deterministic)
}
func (m *ListStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStatus.Merge(m, src)
}
func (m *ListStatus) XXX_Size() int {
	return xxx_messageInfo_ListStatus.Size(m)
}
func (m *ListStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ListStatus proto.InternalMessageInfo

func (m *ListStatus) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *ListStatus) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *ListStatus) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func (m *ListStatus) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ListStatus) GetListStatusType() string {
	if m != nil {
		return m.ListStatusType
	}
	return ""
}

func (m *ListStatus) GetListOrderStatus() string {
	if m != nil {
		return m.ListOrderStatus
	}
	return ""
}

func (m *ListStatus) GetContingencyType() string {
	if m != nil {
		return m.ContingencyType
	}
	return ""
}

func (m *ListStatus) GetListRejectReason() string {
	if m != nil {
		return m.ListRejectReason
	}
	return ""
}

func (m *ListStatus) GetListRejectOrder() *ExecutionReport {
	if m != nil {
		return m.ListRejectOrder
	}
	return nil
}

func (m *ListStatus) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *ListStatus) GetListStatusText() string {
	if m != nil {
		return m.ListStatusText
	}
	return ""
}

func init() {
	proto.RegisterType((*TriggeringInstruction)(nil), "api.TriggeringInstruction")
	proto.RegisterType((*Partie)(nil), "api.Partie")
	proto.RegisterType((*SLTP)(nil), "api.SLTP")
	proto.RegisterType((*NewOrderSingle)(nil), "api.NewOrderSingle")
	proto.RegisterType((*ExecutionReport)(nil), "api.ExecutionReport")
	proto.RegisterType((*OrderCancelRequest)(nil), "api.OrderCancelRequest")
	proto.RegisterType((*OrderCancelReject)(nil), "api.OrderCancelReject")
	proto.RegisterType((*OrderMassCancelRequest)(nil), "api.OrderMassCancelRequest")
	proto.RegisterType((*OrderMassCancelReport)(nil), "api.OrderMassCancelReport")
	proto.RegisterType((*OrderStatusRequest)(nil), "api.OrderStatusRequest")
	proto.RegisterType((*Reject)(nil), "api.Reject")
	proto.RegisterType((*OrderMassStatusResponse)(nil), "api.OrderMassStatusResponse")
	proto.RegisterType((*OrderCancelReplaceRequest)(nil), "api.OrderCancelReplaceRequest")
	proto.RegisterType((*NewOrderList)(nil), "api.NewOrderList")
	proto.RegisterType((*OrderListAction)(nil), "api.OrderListAction")
	proto.RegisterType((*ListStatus)(nil), "api.ListStatus")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 1631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcd, 0x8f, 0x1b, 0x45,
	0x16, 0x97, 0xc7, 0x1e, 0x7b, 0xfc, 0xec, 0x19, 0x4f, 0x2a, 0x33, 0x93, 0x4a, 0x76, 0x93, 0x78,
	0x9d, 0x4d, 0x66, 0xa2, 0x6c, 0xb2, 0xda, 0x8d, 0xb2, 0x59, 0xed, 0x22, 0x45, 0x13, 0x27, 0x41,
	0x96, 0x66, 0xc6, 0xa6, 0x6d, 0xe5, 0xc2, 0xa9, 0xd3, 0x5d, 0x63, 0x75, 0xd4, 0xdd, 0xd5, 0xe9,
	0x2e, 0x0f, 0xf6, 0x7f, 0x80, 0x90, 0xe0, 0xc0, 0xe7, 0x95, 0x03, 0x12, 0x12, 0x12, 0x0a, 0x42,
	0xe2, 0x82, 0x38, 0x70, 0x40, 0x90, 0x03, 0x1c, 0x50, 0x4e, 0x20, 0x24, 0xb8, 0x86, 0x90, 0x48,
	0x48, 0x70, 0x41, 0x1c, 0xd0, 0xab, 0xea, 0xb6, 0xbb, 0x67, 0x6c, 0xcf, 0x57, 0x42, 0x04, 0xb7,
	0x7e, 0xbf, 0xf7, 0xaa, 0xeb, 0x7d, 0xd7, 0xab, 0x82, 0x02, 0xf7, 0x4d, 0xe6, 0x9f, 0xf3, 0x7c,
	0x2e, 0x38, 0x49, 0xeb, 0x9e, 0x55, 0x79, 0x3b, 0x05, 0xf3, 0x2d, 0xdf, 0x6a, 0xb7, 0x99, 0x6f,
	0xb9, 0xed, 0x9a, 0x1b, 0x08, 0xbf, 0x63, 0x08, 0x8b, 0xbb, 0xe4, 0x38, 0x80, 0xc6, 0xd6, 0xab,
	0x76, 0xdd, 0x37, 0x6b, 0x26, 0x7d, 0x69, 0xa6, 0x9c, 0x5a, 0xca, 0x6b, 0xe0, 0x23, 0xc4, 0x11,
	0x22, 0x27, 0x61, 0x3a, 0x5c, 0xb9, 0x2c, 0x57, 0xd0, 0x2f, 0xa6, 0xa4, 0xcc, 0xb4, 0x88, 0xa3,
	0xe4, 0x6f, 0x50, 0x08, 0xc5, 0x5a, 0x3d, 0x8f, 0xd1, 0xcf, 0x95, 0x50, 0x41, 0x0c, 0x30, 0x72,
	0x02, 0x8a, 0xa1, 0x48, 0xd3, 0xe0, 0x1e, 0xa3, 0xdf, 0x14, 0xa5, 0x4c, 0x51, 0xc4, 0xc0, 0xca,
	0x55, 0xc8, 0x36, 0x74, 0x5f, 0x58, 0x8c, 0xfc, 0x05, 0xa6, 0xd4, 0x57, 0xcd, 0xa4, 0x1f, 0xa7,
	0xa5, 0xe8, 0x94, 0x17, 0x02, 0xe4, 0x18, 0x80, 0x62, 0x6a, 0xdc, 0x66, 0xf4, 0xac, 0xd2, 0xda,
	0xeb, 0x23, 0x95, 0xef, 0x52, 0x90, 0x69, 0xae, 0xb4, 0x1a, 0x84, 0x42, 0xae, 0xee, 0x9b, 0x52,
	0xa7, 0x25, 0x29, 0x95, 0xe3, 0x8a, 0x24, 0x73, 0x30, 0xd9, 0xf0, 0x2d, 0x83, 0xd1, 0x7f, 0x48,
	0x7c, 0xd2, 0x43, 0x82, 0x2c, 0x40, 0xb6, 0x29, 0xb8, 0xd7, 0xe8, 0x52, 0x43, 0xc2, 0xd9, 0x40,
	0x52, 0xa8, 0x4d, 0x55, 0xf7, 0xd4, 0x82, 0xdb, 0x79, 0xa5, 0x8d, 0x11, 0x02, 0x68, 0x59, 0x83,
	0xb5, 0xe5, 0xb7, 0xdc, 0xe9, 0x53, 0x65, 0x7d, 0xd1, 0x8b, 0x81, 0xe8, 0xc8, 0x06, 0x6b, 0xd7,
	0xd7, 0xd7, 0x03, 0x26, 0xa4, 0xd4, 0x27, 0x59, 0xe5, 0x48, 0x2f, 0x8e, 0x92, 0x45, 0x98, 0xe9,
	0x8b, 0x5d, 0xd7, 0xed, 0x0e, 0xa3, 0x77, 0x53, 0x52, 0x6e, 0xc6, 0x4b, 0xc0, 0x95, 0x0f, 0xb2,
	0x30, 0xb3, 0xc6, 0x9e, 0xab, 0x63, 0xac, 0x9b, 0x96, 0xdb, 0xb6, 0x19, 0x1a, 0xbb, 0x1a, 0xb4,
	0xe5, 0xcf, 0x4f, 0x28, 0x63, 0x1d, 0x45, 0x22, 0x27, 0x8a, 0x71, 0x41, 0x71, 0x0c, 0x45, 0x86,
	0x0e, 0x62, 0x7e, 0xcd, 0xa4, 0x27, 0xfb, 0x0e, 0x42, 0x52, 0xba, 0xa2, 0xe7, 0xdc, 0xe0, 0x36,
	0xbd, 0x18, 0xba, 0x42, 0x52, 0x84, 0x40, 0xa6, 0x69, 0x99, 0x8c, 0xfe, 0x47, 0xa2, 0x99, 0xc0,
	0x32, 0x19, 0xf9, 0x2b, 0xe4, 0x9b, 0x4c, 0x08, 0x5b, 0xee, 0x7d, 0x49, 0x32, 0xf2, 0x41, 0x04,
	0x90, 0x0a, 0x46, 0x5e, 0x77, 0x03, 0xdd, 0x10, 0x2d, 0xcb, 0x61, 0xf4, 0xa9, 0x72, 0x6a, 0x29,
	0x8d, 0x81, 0x1f, 0x60, 0xf8, 0x87, 0x15, 0x2b, 0x10, 0x4d, 0x76, 0x6b, 0x8d, 0xd3, 0x6a, 0x39,
	0xb5, 0x34, 0xa9, 0xe5, 0xed, 0x08, 0x20, 0x47, 0x60, 0x4a, 0x6a, 0xf9, 0x8c, 0xe8, 0xd1, 0x53,
	0xca, 0xfb, 0x3c, 0xa4, 0x7f, 0x9f, 0x10, 0x53, 0xc8, 0x2d, 0x1b, 0x06, 0xef, 0xb8, 0x82, 0x62,
	0x38, 0x32, 0x5a, 0x4e, 0x57, 0x24, 0xaa, 0x76, 0xb5, 0xcb, 0x0c, 0x2c, 0x2a, 0x4a, 0xca, 0x69,
	0x5c, 0xc5, 0x42, 0x9a, 0x94, 0xa1, 0x80, 0xc6, 0xd5, 0xdc, 0x6b, 0xdc, 0x37, 0x18, 0xfd, 0x7f,
	0x58, 0x14, 0x03, 0x88, 0x9c, 0x86, 0x52, 0x95, 0x3b, 0x8e, 0x15, 0x04, 0x16, 0x77, 0x57, 0xd8,
	0x06, 0xb3, 0xe9, 0x67, 0x87, 0xa4, 0x58, 0xc9, 0x48, 0xe2, 0x4f, 0x24, 0xcb, 0x48, 0x13, 0x16,
	0x86, 0x36, 0x8e, 0x80, 0x7e, 0x3d, 0x55, 0x4e, 0x2f, 0x15, 0xfe, 0x7d, 0xe4, 0x9c, 0xee, 0x59,
	0xe7, 0x86, 0xca, 0x68, 0x0b, 0x62, 0xe8, 0x52, 0x6c, 0x3a, 0x0d, 0x1e, 0x58, 0x48, 0xd4, 0x4c,
	0xfa, 0xe1, 0x9c, 0x74, 0x28, 0x78, 0x7d, 0x88, 0x9c, 0x82, 0x99, 0x48, 0xe0, 0xea, 0xfa, 0x3a,
	0x33, 0x04, 0x5d, 0x0d, 0xb5, 0x4b, 0xa0, 0xe4, 0x98, 0xaa, 0x72, 0xfa, 0xfc, 0xa2, 0xd4, 0x25,
	0x2f, 0x75, 0x41, 0x44, 0xcb, 0x04, 0xb6, 0xf0, 0x30, 0x55, 0x5b, 0xac, 0x2b, 0xe8, 0xff, 0x54,
	0xaa, 0x0a, 0xd6, 0x15, 0x95, 0x3b, 0x05, 0x28, 0x61, 0xc0, 0x3a, 0x52, 0x45, 0xe6, 0x71, 0x5f,
	0x8c, 0x2f, 0x9c, 0x11, 0x71, 0x1f, 0x5d, 0x52, 0x65, 0x28, 0xd4, 0x7d, 0xab, 0x1d, 0x71, 0x4f,
	0xab, 0xa8, 0xf3, 0x01, 0x34, 0xbe, 0xe8, 0xb0, 0x0c, 0x6a, 0x26, 0xbd, 0xac, 0x92, 0xd3, 0x96,
	0xd4, 0xc8, 0x62, 0x7c, 0x54, 0xc9, 0xbf, 0xbf, 0x2c, 0xde, 0x49, 0x81, 0x2f, 0x40, 0x56, 0xee,
	0x60, 0xd2, 0x03, 0x6a, 0x67, 0xf9, 0x7f, 0x13, 0xcb, 0x0e, 0x71, 0x69, 0xc2, 0xeb, 0x2a, 0x09,
	0xe5, 0xd6, 0xd2, 0x88, 0x0b, 0x30, 0x8f, 0x4c, 0x8d, 0x05, 0x42, 0x17, 0xcc, 0x61, 0xae, 0xd0,
	0x98, 0x1e, 0x70, 0x97, 0xfe, 0x32, 0x21, 0x25, 0xe7, 0xd9, 0x30, 0x2e, 0x39, 0x0c, 0xb9, 0x96,
	0xaf, 0x9b, 0x78, 0x74, 0xdc, 0xcf, 0x29, 0xb7, 0x08, 0x45, 0x63, 0x9f, 0xa9, 0xfb, 0x66, 0x53,
	0xe8, 0xa2, 0x13, 0xd0, 0x45, 0xd5, 0xa9, 0x78, 0x04, 0xa0, 0x21, 0x75, 0xdf, 0xd4, 0xd8, 0xcd,
	0x70, 0x9b, 0xb6, 0x2a, 0x31, 0x1e, 0xc3, 0x86, 0xf6, 0xbf, 0x71, 0xfd, 0xe9, 0x28, 0xe4, 0x57,
	0x98, 0xbe, 0xc1, 0x02, 0x64, 0xbe, 0xa1, 0x2c, 0xcc, 0xdb, 0x11, 0x82, 0x7e, 0xa9, 0x76, 0x1c,
	0xe4, 0xa9, 0xc3, 0x37, 0x6b, 0x48, 0x0a, 0x23, 0xbb, 0xa2, 0x07, 0x02, 0x19, 0x65, 0x65, 0x82,
	0xad, 0xc8, 0xf1, 0x8d, 0x0a, 0x13, 0x48, 0x0f, 0x44, 0xa3, 0x4b, 0x8f, 0x87, 0x09, 0x24, 0x29,
	0x4c, 0x87, 0xe5, 0x8d, 0x76, 0xa3, 0x4b, 0x55, 0x3f, 0x98, 0xd4, 0x91, 0x20, 0xe7, 0x61, 0xae,
	0xaa, 0xdb, 0x46, 0xc7, 0xd6, 0x05, 0x33, 0xab, 0x46, 0x2f, 0xda, 0xf1, 0x4d, 0xd5, 0x5b, 0xe6,
	0x8c, 0x21, 0x4c, 0x34, 0xb6, 0xda, 0xf1, 0x7d, 0xe6, 0x1a, 0x3d, 0x5a, 0x0a, 0xb7, 0x0f, 0x69,
	0xf2, 0x77, 0x98, 0x96, 0x07, 0x41, 0x5f, 0xa0, 0xab, 0xda, 0x4f, 0x10, 0x07, 0xb7, 0x39, 0x2e,
	0x8e, 0xc0, 0xd4, 0x1a, 0x13, 0xab, 0xdc, 0x65, 0x3d, 0xba, 0xa1, 0xfe, 0xef, 0x86, 0x34, 0x39,
	0x03, 0xb3, 0xa8, 0xc6, 0x8a, 0x75, 0xab, 0x63, 0x99, 0x96, 0xe8, 0xd5, 0x5c, 0x93, 0xde, 0x55,
	0x26, 0xcd, 0xda, 0x9b, 0x18, 0x38, 0x25, 0x0c, 0x9a, 0x2b, 0x55, 0xe3, 0x06, 0x0c, 0xda, 0xaa,
	0x74, 0x24, 0x77, 0x1c, 0x4d, 0x17, 0x8c, 0x7e, 0x19, 0x39, 0x32, 0x04, 0xb0, 0xdd, 0x22, 0xb3,
	0x6f, 0xc8, 0xb7, 0x6a, 0x06, 0x29, 0x1a, 0x31, 0x50, 0x8d, 0x4f, 0x37, 0x99, 0x21, 0x64, 0x9b,
	0x79, 0x0f, 0xa2, 0xf1, 0x29, 0x82, 0x9e, 0x4c, 0xd3, 0x7e, 0x64, 0xfd, 0xf5, 0x28, 0xe4, 0x57,
	0x75, 0xbf, 0x6d, 0xb9, 0xcb, 0x8e, 0xa0, 0x0f, 0x94, 0x03, 0xf3, 0x4e, 0x84, 0xa0, 0xde, 0x7d,
	0xb6, 0xd4, 0xfb, 0x07, 0x25, 0x32, 0xed, 0xc4, 0x51, 0xf4, 0x41, 0x5f, 0xac, 0x6a, 0xf4, 0xe8,
	0xc3, 0x70, 0xf0, 0x73, 0x62, 0xe0, 0x9e, 0x5a, 0xf9, 0xc3, 0x14, 0x10, 0x59, 0x76, 0x55, 0xdd,
	0x35, 0x98, 0xad, 0xb1, 0x5b, 0x1d, 0x16, 0x88, 0x3d, 0x8d, 0x41, 0xfb, 0xec, 0xd9, 0x3b, 0x1e,
	0x94, 0x76, 0xd2, 0x29, 0x47, 0x9e, 0x39, 0x95, 0x7b, 0x13, 0x70, 0x20, 0x61, 0x30, 0xe6, 0xd9,
	0x9e, 0x4e, 0xaf, 0x31, 0xe7, 0xc9, 0x63, 0xf0, 0xd0, 0xf8, 0xa6, 0x7b, 0x06, 0x66, 0xab, 0x5d,
	0x5b, 0x36, 0xd8, 0xc0, 0xe3, 0x6e, 0xc0, 0x5a, 0x9c, 0xbe, 0xaf, 0xaa, 0x6d, 0xd6, 0xd8, 0xc4,
	0x40, 0x07, 0x46, 0xc2, 0xb2, 0x43, 0xaf, 0x87, 0x55, 0x19, 0xc3, 0xb6, 0xaf, 0xca, 0x1d, 0x44,
	0xa1, 0xf2, 0x63, 0x0a, 0x16, 0xa4, 0x39, 0xab, 0x7a, 0x10, 0xec, 0x3f, 0xc1, 0x2e, 0xc0, 0xfc,
	0x96, 0x1f, 0xc9, 0x3f, 0xbc, 0x9c, 0x51, 0x27, 0x99, 0x33, 0x8c, 0xbb, 0xab, 0xdc, 0xda, 0x69,
	0x55, 0x8f, 0xce, 0xaf, 0xb7, 0xd2, 0x30, 0xbf, 0xc5, 0xe6, 0xed, 0x27, 0xa4, 0x11, 0x26, 0xff,
	0x13, 0x08, 0xfe, 0x47, 0xdd, 0x10, 0xd5, 0x7f, 0x6a, 0x57, 0xe8, 0x57, 0x2a, 0x1c, 0xc4, 0xd9,
	0xc2, 0x8a, 0x16, 0x44, 0x1b, 0xab, 0x98, 0xd3, 0x57, 0x32, 0x83, 0x05, 0x49, 0x16, 0xb9, 0x08,
	0x0b, 0xf1, 0x05, 0x18, 0xdf, 0x30, 0x2d, 0x5e, 0x55, 0x8b, 0x16, 0x9c, 0xa1, 0xec, 0xed, 0x33,
	0xe4, 0x51, 0xd7, 0xf4, 0xbf, 0xe0, 0x60, 0x8b, 0x0b, 0xdd, 0x5e, 0x96, 0x21, 0x60, 0xa6, 0xf4,
	0x72, 0x40, 0x5f, 0xcb, 0x48, 0xd9, 0x83, 0x62, 0x2b, 0x6f, 0x4c, 0x98, 0x82, 0xb0, 0xed, 0xa9,
	0xfa, 0xd9, 0x3e, 0x2b, 0x4f, 0x43, 0x09, 0xdd, 0xd4, 0x17, 0xaf, 0x99, 0xf4, 0x8e, 0xf2, 0x4f,
	0xc9, 0x49, 0xe2, 0x63, 0x36, 0x7d, 0x16, 0xb2, 0xdb, 0xf6, 0x9b, 0x13, 0x50, 0x4c, 0x44, 0xe1,
	0x57, 0x35, 0xa5, 0x15, 0xfd, 0xb8, 0xef, 0x87, 0x75, 0xf2, 0x17, 0x27, 0xe0, 0x50, 0x3f, 0xf1,
	0x22, 0x7d, 0xc2, 0x20, 0x3f, 0x5e, 0xbb, 0xc8, 0x59, 0xc8, 0x86, 0xc1, 0xf8, 0x29, 0x2f, 0x8f,
	0x9e, 0x39, 0x79, 0xf4, 0x6c, 0xba, 0x22, 0x68, 0x59, 0xae, 0xa2, 0x72, 0x06, 0x26, 0xaf, 0x59,
	0xb6, 0x1d, 0xd0, 0x9f, 0xc7, 0x49, 0x4f, 0xae, 0xa3, 0xcc, 0x3e, 0xfc, 0x91, 0x81, 0xc3, 0x89,
	0x46, 0xef, 0xd9, 0xba, 0xc1, 0xfe, 0xf4, 0x07, 0xdc, 0xd8, 0x6b, 0xc8, 0xb8, 0x19, 0xfb, 0x0f,
	0xfe, 0x98, 0xb3, 0xdd, 0xf4, 0x53, 0x79, 0x30, 0x01, 0xc5, 0xe8, 0xb1, 0x07, 0xef, 0x87, 0x63,
	0x52, 0x60, 0xd4, 0x0d, 0xf2, 0x30, 0xe4, 0x2e, 0x5b, 0xea, 0xa6, 0xf8, 0x82, 0x3a, 0x5c, 0x73,
	0x37, 0x14, 0x2d, 0x2f, 0x78, 0x5c, 0xac, 0xf1, 0xb0, 0x0e, 0xae, 0xc8, 0xd7, 0x97, 0x82, 0x18,
	0x40, 0xea, 0x99, 0xc2, 0x15, 0x96, 0xdb, 0xc6, 0xb1, 0x57, 0xfe, 0xe4, 0x1e, 0x44, 0xcf, 0x14,
	0x09, 0x9c, 0x9c, 0x07, 0xc0, 0xfd, 0xeb, 0xbe, 0xf9, 0xb4, 0xef, 0xd1, 0x9a, 0xb4, 0xe7, 0xa0,
	0xb4, 0x27, 0xf9, 0x5a, 0xa5, 0x81, 0xdd, 0x17, 0x23, 0xff, 0x85, 0xe9, 0x35, 0x16, 0x08, 0x66,
	0xe2, 0x52, 0x5c, 0xf7, 0x60, 0x5a, 0x2e, 0x3c, 0x90, 0x58, 0x88, 0x4c, 0x6d, 0xda, 0x8d, 0x0b,
	0x8e, 0xcc, 0xcd, 0xfd, 0x0d, 0x5a, 0xd7, 0xa1, 0xd4, 0xdf, 0x31, 0x7c, 0xe1, 0xdc, 0x85, 0x0b,
	0x12, 0x95, 0x94, 0x8e, 0x55, 0x52, 0xe5, 0x9d, 0xb4, 0xf2, 0x4e, 0x38, 0xf9, 0xec, 0x71, 0x72,
	0xdb, 0xd5, 0x0b, 0xc1, 0x22, 0xcc, 0x0c, 0x76, 0x94, 0x5b, 0xbd, 0xab, 0xc2, 0x3f, 0x63, 0x27,
	0x60, 0x34, 0x30, 0x0c, 0x5c, 0x74, 0xb2, 0xd0, 0xdb, 0x4a, 0xb2, 0x64, 0x27, 0xf1, 0xdd, 0xf8,
	0x02, 0x2f, 0x6c, 0x18, 0xb6, 0x78, 0x1b, 0xfc, 0x1e, 0xc2, 0x0b, 0xdb, 0x26, 0x06, 0xb9, 0xa4,
	0x54, 0x50, 0x98, 0xdc, 0x90, 0xde, 0x47, 0xd9, 0x51, 0x6d, 0xb6, 0x64, 0x27, 0xa5, 0x77, 0x14,
	0xf5, 0xa4, 0x43, 0xb0, 0xf3, 0x7e, 0xb4, 0xd5, 0x21, 0xac, 0x2b, 0x6e, 0x64, 0xe5, 0x0b, 0xfa,
	0xf9, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x02, 0xcd, 0xc3, 0x50, 0x17, 0x00, 0x00,
}
