// Code generated by protoc-gen-go. DO NOT EDIT.
// source: positions.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	PaymentType          string   `protobuf:"bytes,40213,opt,name=PaymentType,json=paymentType,proto3" json:"PaymentType,omitempty"`
	PaymentCurrency      string   `protobuf:"bytes,40216,opt,name=PaymentCurrency,json=paymentCurrency,proto3" json:"PaymentCurrency,omitempty"`
	PaymentAmount        string   `protobuf:"bytes,40217,opt,name=PaymentAmount,json=paymentAmount,proto3" json:"PaymentAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetPaymentType() string {
	if m != nil {
		return m.PaymentType
	}
	return ""
}

func (m *Payment) GetPaymentCurrency() string {
	if m != nil {
		return m.PaymentCurrency
	}
	return ""
}

func (m *Payment) GetPaymentAmount() string {
	if m != nil {
		return m.PaymentAmount
	}
	return ""
}

type RelatedTrade struct {
	RelatedTradeId       string   `protobuf:"bytes,1856,opt,name=RelatedTradeId,json=relatedTradeId,proto3" json:"RelatedTradeId,omitempty"`
	RelatedTradeType     string   `protobuf:"bytes,1857,opt,name=RelatedTradeType,json=relatedTradeType,proto3" json:"RelatedTradeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelatedTrade) Reset()         { *m = RelatedTrade{} }
func (m *RelatedTrade) String() string { return proto.CompactTextString(m) }
func (*RelatedTrade) ProtoMessage()    {}
func (*RelatedTrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{1}
}

func (m *RelatedTrade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelatedTrade.Unmarshal(m, b)
}
func (m *RelatedTrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelatedTrade.Marshal(b, m, deterministic)
}
func (m *RelatedTrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelatedTrade.Merge(m, src)
}
func (m *RelatedTrade) XXX_Size() int {
	return xxx_messageInfo_RelatedTrade.Size(m)
}
func (m *RelatedTrade) XXX_DiscardUnknown() {
	xxx_messageInfo_RelatedTrade.DiscardUnknown(m)
}

var xxx_messageInfo_RelatedTrade proto.InternalMessageInfo

func (m *RelatedTrade) GetRelatedTradeId() string {
	if m != nil {
		return m.RelatedTradeId
	}
	return ""
}

func (m *RelatedTrade) GetRelatedTradeType() string {
	if m != nil {
		return m.RelatedTradeType
	}
	return ""
}

type PositionReport struct {
	MsgType                      string          `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	Account                      uint64          `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	PositionId                   uint64          `protobuf:"varint,2618,opt,name=PositionId,json=positionId,proto3" json:"PositionId,omitempty"`
	TransactTime                 int64           `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	Symbol                       string          `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	PositionOpenTime             int64           `protobuf:"varint,1805,opt,name=PositionOpenTime,json=positionOpenTime,proto3" json:"PositionOpenTime,omitempty"`
	AvgPx                        string          `protobuf:"bytes,6,opt,name=AvgPx,json=avgPx,proto3" json:"AvgPx,omitempty"`
	Volume                       string          `protobuf:"bytes,53,opt,name=Volume,json=volume,proto3" json:"Volume,omitempty"`
	Side                         string          `protobuf:"bytes,54,opt,name=Side,json=side,proto3" json:"Side,omitempty"`
	SettlDate                    int64           `protobuf:"varint,64,opt,name=SettlDate,json=settlDate,proto3" json:"SettlDate,omitempty"`
	SettlPrice                   string          `protobuf:"bytes,730,opt,name=SettlPrice,json=settlPrice,proto3" json:"SettlPrice,omitempty"`
	PriorSettlPrice              string          `protobuf:"bytes,734,opt,name=PriorSettlPrice,json=priorSettlPrice,proto3" json:"PriorSettlPrice,omitempty"`
	PreviousClearingBusinessDate int64           `protobuf:"varint,1084,opt,name=PreviousClearingBusinessDate,json=previousClearingBusinessDate,proto3" json:"PreviousClearingBusinessDate,omitempty"`
	ClearingBusinessDate         int64           `protobuf:"varint,715,opt,name=ClearingBusinessDate,json=clearingBusinessDate,proto3" json:"ClearingBusinessDate,omitempty"`
	MarginAmounts                []*MarginAmount `protobuf:"bytes,1643,rep,name=MarginAmounts,json=marginAmounts,proto3" json:"MarginAmounts,omitempty"`
	Payments                     []*Payment      `protobuf:"bytes,40212,rep,name=Payments,json=payments,proto3" json:"Payments,omitempty"`
	RelatedTrades                []*RelatedTrade `protobuf:"bytes,1855,rep,name=RelatedTrades,json=relatedTrades,proto3" json:"RelatedTrades,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}        `json:"-"`
	XXX_unrecognized             []byte          `json:"-"`
	XXX_sizecache                int32           `json:"-"`
}

func (m *PositionReport) Reset()         { *m = PositionReport{} }
func (m *PositionReport) String() string { return proto.CompactTextString(m) }
func (*PositionReport) ProtoMessage()    {}
func (*PositionReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{2}
}

func (m *PositionReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionReport.Unmarshal(m, b)
}
func (m *PositionReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionReport.Marshal(b, m, deterministic)
}
func (m *PositionReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionReport.Merge(m, src)
}
func (m *PositionReport) XXX_Size() int {
	return xxx_messageInfo_PositionReport.Size(m)
}
func (m *PositionReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionReport.DiscardUnknown(m)
}

var xxx_messageInfo_PositionReport proto.InternalMessageInfo

func (m *PositionReport) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *PositionReport) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *PositionReport) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *PositionReport) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *PositionReport) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *PositionReport) GetPositionOpenTime() int64 {
	if m != nil {
		return m.PositionOpenTime
	}
	return 0
}

func (m *PositionReport) GetAvgPx() string {
	if m != nil {
		return m.AvgPx
	}
	return ""
}

func (m *PositionReport) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *PositionReport) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *PositionReport) GetSettlDate() int64 {
	if m != nil {
		return m.SettlDate
	}
	return 0
}

func (m *PositionReport) GetSettlPrice() string {
	if m != nil {
		return m.SettlPrice
	}
	return ""
}

func (m *PositionReport) GetPriorSettlPrice() string {
	if m != nil {
		return m.PriorSettlPrice
	}
	return ""
}

func (m *PositionReport) GetPreviousClearingBusinessDate() int64 {
	if m != nil {
		return m.PreviousClearingBusinessDate
	}
	return 0
}

func (m *PositionReport) GetClearingBusinessDate() int64 {
	if m != nil {
		return m.ClearingBusinessDate
	}
	return 0
}

func (m *PositionReport) GetMarginAmounts() []*MarginAmount {
	if m != nil {
		return m.MarginAmounts
	}
	return nil
}

func (m *PositionReport) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func (m *PositionReport) GetRelatedTrades() []*RelatedTrade {
	if m != nil {
		return m.RelatedTrades
	}
	return nil
}

type MassPositionReport struct {
	MsgType         string            `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	PosReqId        string            `protobuf:"bytes,710,opt,name=PosReqId,json=posReqId,proto3" json:"PosReqId,omitempty"`
	Account         uint64            `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	TransactTime    int64             `protobuf:"varint,60,opt,name=TransactTime,json=transactTime,proto3" json:"TransactTime,omitempty"`
	OpenPositions   []*PositionReport `protobuf:"bytes,727,rep,name=OpenPositions,json=openPositions,proto3" json:"OpenPositions,omitempty"`
	PositionHistory []*PositionReport `protobuf:"bytes,726,rep,name=PositionHistory,json=positionHistory,proto3" json:"PositionHistory,omitempty"`
	// reject fields
	RejectReason         string   `protobuf:"bytes,380,opt,name=RejectReason,json=rejectReason,proto3" json:"RejectReason,omitempty"`
	Text                 string   `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MassPositionReport) Reset()         { *m = MassPositionReport{} }
func (m *MassPositionReport) String() string { return proto.CompactTextString(m) }
func (*MassPositionReport) ProtoMessage()    {}
func (*MassPositionReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{3}
}

func (m *MassPositionReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MassPositionReport.Unmarshal(m, b)
}
func (m *MassPositionReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MassPositionReport.Marshal(b, m, deterministic)
}
func (m *MassPositionReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MassPositionReport.Merge(m, src)
}
func (m *MassPositionReport) XXX_Size() int {
	return xxx_messageInfo_MassPositionReport.Size(m)
}
func (m *MassPositionReport) XXX_DiscardUnknown() {
	xxx_messageInfo_MassPositionReport.DiscardUnknown(m)
}

var xxx_messageInfo_MassPositionReport proto.InternalMessageInfo

func (m *MassPositionReport) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MassPositionReport) GetPosReqId() string {
	if m != nil {
		return m.PosReqId
	}
	return ""
}

func (m *MassPositionReport) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *MassPositionReport) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *MassPositionReport) GetOpenPositions() []*PositionReport {
	if m != nil {
		return m.OpenPositions
	}
	return nil
}

func (m *MassPositionReport) GetPositionHistory() []*PositionReport {
	if m != nil {
		return m.PositionHistory
	}
	return nil
}

func (m *MassPositionReport) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

func (m *MassPositionReport) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PositionsRequest struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	PosReqId             string   `protobuf:"bytes,710,opt,name=PosReqId,json=posReqId,proto3" json:"PosReqId,omitempty"`
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionsRequest) Reset()         { *m = PositionsRequest{} }
func (m *PositionsRequest) String() string { return proto.CompactTextString(m) }
func (*PositionsRequest) ProtoMessage()    {}
func (*PositionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{4}
}

func (m *PositionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionsRequest.Unmarshal(m, b)
}
func (m *PositionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionsRequest.Marshal(b, m, deterministic)
}
func (m *PositionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionsRequest.Merge(m, src)
}
func (m *PositionsRequest) XXX_Size() int {
	return xxx_messageInfo_PositionsRequest.Size(m)
}
func (m *PositionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PositionsRequest proto.InternalMessageInfo

func (m *PositionsRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *PositionsRequest) GetPosReqId() string {
	if m != nil {
		return m.PosReqId
	}
	return ""
}

func (m *PositionsRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type PositionMaintenanceRequest struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	PosReqId             string   `protobuf:"bytes,710,opt,name=PosReqId,json=posReqId,proto3" json:"PosReqId,omitempty"`
	PosTransType         string   `protobuf:"bytes,709,opt,name=PosTransType,json=posTransType,proto3" json:"PosTransType,omitempty"`
	PosMaintAction       string   `protobuf:"bytes,712,opt,name=PosMaintAction,json=posMaintAction,proto3" json:"PosMaintAction,omitempty"`
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	Symbol               string   `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionMaintenanceRequest) Reset()         { *m = PositionMaintenanceRequest{} }
func (m *PositionMaintenanceRequest) String() string { return proto.CompactTextString(m) }
func (*PositionMaintenanceRequest) ProtoMessage()    {}
func (*PositionMaintenanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{5}
}

func (m *PositionMaintenanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionMaintenanceRequest.Unmarshal(m, b)
}
func (m *PositionMaintenanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionMaintenanceRequest.Marshal(b, m, deterministic)
}
func (m *PositionMaintenanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionMaintenanceRequest.Merge(m, src)
}
func (m *PositionMaintenanceRequest) XXX_Size() int {
	return xxx_messageInfo_PositionMaintenanceRequest.Size(m)
}
func (m *PositionMaintenanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionMaintenanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PositionMaintenanceRequest proto.InternalMessageInfo

func (m *PositionMaintenanceRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *PositionMaintenanceRequest) GetPosReqId() string {
	if m != nil {
		return m.PosReqId
	}
	return ""
}

func (m *PositionMaintenanceRequest) GetPosTransType() string {
	if m != nil {
		return m.PosTransType
	}
	return ""
}

func (m *PositionMaintenanceRequest) GetPosMaintAction() string {
	if m != nil {
		return m.PosMaintAction
	}
	return ""
}

func (m *PositionMaintenanceRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *PositionMaintenanceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type PositionMaintenanceReport struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	PosReqId             string   `protobuf:"bytes,710,opt,name=PosReqId,json=posReqId,proto3" json:"PosReqId,omitempty"`
	PosTransType         string   `protobuf:"bytes,709,opt,name=PosTransType,json=posTransType,proto3" json:"PosTransType,omitempty"`
	PosMaintAction       string   `protobuf:"bytes,712,opt,name=PosMaintAction,json=posMaintAction,proto3" json:"PosMaintAction,omitempty"`
	Account              uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	Symbol               string   `protobuf:"bytes,55,opt,name=Symbol,json=symbol,proto3" json:"Symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionMaintenanceReport) Reset()         { *m = PositionMaintenanceReport{} }
func (m *PositionMaintenanceReport) String() string { return proto.CompactTextString(m) }
func (*PositionMaintenanceReport) ProtoMessage()    {}
func (*PositionMaintenanceReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_86e2827456090109, []int{6}
}

func (m *PositionMaintenanceReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionMaintenanceReport.Unmarshal(m, b)
}
func (m *PositionMaintenanceReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionMaintenanceReport.Marshal(b, m, deterministic)
}
func (m *PositionMaintenanceReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionMaintenanceReport.Merge(m, src)
}
func (m *PositionMaintenanceReport) XXX_Size() int {
	return xxx_messageInfo_PositionMaintenanceReport.Size(m)
}
func (m *PositionMaintenanceReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionMaintenanceReport.DiscardUnknown(m)
}

var xxx_messageInfo_PositionMaintenanceReport proto.InternalMessageInfo

func (m *PositionMaintenanceReport) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *PositionMaintenanceReport) GetPosReqId() string {
	if m != nil {
		return m.PosReqId
	}
	return ""
}

func (m *PositionMaintenanceReport) GetPosTransType() string {
	if m != nil {
		return m.PosTransType
	}
	return ""
}

func (m *PositionMaintenanceReport) GetPosMaintAction() string {
	if m != nil {
		return m.PosMaintAction
	}
	return ""
}

func (m *PositionMaintenanceReport) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *PositionMaintenanceReport) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "api.Payment")
	proto.RegisterType((*RelatedTrade)(nil), "api.RelatedTrade")
	proto.RegisterType((*PositionReport)(nil), "api.PositionReport")
	proto.RegisterType((*MassPositionReport)(nil), "api.MassPositionReport")
	proto.RegisterType((*PositionsRequest)(nil), "api.PositionsRequest")
	proto.RegisterType((*PositionMaintenanceRequest)(nil), "api.PositionMaintenanceRequest")
	proto.RegisterType((*PositionMaintenanceReport)(nil), "api.PositionMaintenanceReport")
}

func init() { proto.RegisterFile("positions.proto", fileDescriptor_86e2827456090109) }

var fileDescriptor_86e2827456090109 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0x26, 0x6d, 0x37, 0x49, 0xdf, 0xee, 0x6e, 0xfa, 0x9b, 0x5f, 0x90, 0xb1, 0x16, 0x0c, 0x5b,
	0xd0, 0x58, 0xa1, 0x07, 0x8b, 0x7f, 0x28, 0x22, 0xc6, 0x7a, 0xb0, 0x87, 0xe0, 0xb2, 0x0d, 0xde,
	0xa7, 0xbb, 0x43, 0x18, 0xc9, 0xee, 0x8c, 0x33, 0x93, 0xd2, 0x1c, 0xfd, 0x00, 0xde, 0x2a, 0xe8,
	0x57, 0x29, 0xe2, 0x9f, 0x83, 0x22, 0x78, 0x53, 0x50, 0xf0, 0xe0, 0x17, 0xf0, 0x2b, 0x78, 0x90,
	0x9d, 0xdd, 0xb4, 0x93, 0x52, 0x43, 0xa1, 0x82, 0xb7, 0xbe, 0xcf, 0xfb, 0x3c, 0xef, 0x33, 0xef,
	0xec, 0xd3, 0x09, 0x34, 0x04, 0x57, 0x4c, 0x33, 0x9e, 0xa9, 0x35, 0x21, 0xb9, 0xe6, 0x68, 0x96,
	0x08, 0xb6, 0xe4, 0xa6, 0x44, 0xf6, 0x59, 0x56, 0x40, 0xc1, 0xd3, 0x0a, 0xd4, 0x42, 0x32, 0x4a,
	0x69, 0xa6, 0x51, 0x00, 0x0b, 0xe5, 0x9f, 0xbd, 0x91, 0xa0, 0xf8, 0xf9, 0xc1, 0x4c, 0xab, 0xd2,
	0x9e, 0x8f, 0x16, 0xc4, 0x11, 0x88, 0x56, 0xa1, 0x51, 0x72, 0x36, 0x87, 0x52, 0xd2, 0x2c, 0x1e,
	0xe1, 0x17, 0x25, 0xaf, 0x21, 0x26, 0x1b, 0xe8, 0x12, 0x78, 0x25, 0xb7, 0x93, 0xf2, 0x61, 0xa6,
	0xf1, 0xcb, 0x92, 0xe9, 0x09, 0x1b, 0x0e, 0x12, 0x70, 0x23, 0x3a, 0x20, 0x9a, 0x26, 0x3d, 0x49,
	0x12, 0x8a, 0x2e, 0x83, 0x6f, 0xd7, 0x5b, 0x09, 0x7e, 0xeb, 0x1b, 0x9d, 0x2f, 0x27, 0x60, 0x74,
	0x15, 0x16, 0x6d, 0xa2, 0x39, 0xf5, 0xbb, 0x82, 0xba, 0x28, 0x8f, 0x35, 0x82, 0x7d, 0x07, 0xfc,
	0xb0, 0xbc, 0x90, 0x88, 0x0a, 0x2e, 0x35, 0xc2, 0x50, 0xeb, 0xaa, 0xbe, 0x91, 0xad, 0x18, 0x55,
	0x2d, 0x2d, 0xca, 0xbc, 0xd3, 0x89, 0x63, 0x73, 0xe8, 0x4a, 0xab, 0xd2, 0x9e, 0x8b, 0x6a, 0xa4,
	0x28, 0xd1, 0x45, 0x80, 0xf1, 0x94, 0xad, 0x04, 0x1f, 0x34, 0x4d, 0x17, 0xc4, 0x21, 0x84, 0x02,
	0x70, 0x7b, 0x92, 0x64, 0x8a, 0xc4, 0xba, 0xc7, 0x52, 0x8a, 0x6f, 0xb7, 0x2a, 0xed, 0xd9, 0xc8,
	0xd5, 0x16, 0x86, 0xce, 0x41, 0x75, 0x7b, 0x94, 0xee, 0xf0, 0x01, 0xbe, 0x69, 0x7c, 0xab, 0xca,
	0x54, 0xf9, 0x42, 0xe3, 0xe1, 0x0f, 0x05, 0xcd, 0x8c, 0xfe, 0x99, 0x6f, 0x06, 0x2c, 0x8a, 0x63,
	0x0d, 0xd4, 0x04, 0xa7, 0xb3, 0xdb, 0x0f, 0xf7, 0x70, 0xd5, 0xcc, 0x70, 0x48, 0x5e, 0xe4, 0xa3,
	0x1f, 0xf1, 0xc1, 0x30, 0xa5, 0xf8, 0x7a, 0x31, 0x7a, 0xd7, 0x54, 0x08, 0xc1, 0xdc, 0x36, 0x4b,
	0x28, 0xbe, 0x61, 0xd0, 0x39, 0xc5, 0x12, 0x8a, 0x96, 0x61, 0x7e, 0x9b, 0x6a, 0x3d, 0xb8, 0x4f,
	0x34, 0xc5, 0x77, 0x8d, 0xcd, 0xbc, 0x1a, 0x03, 0xf9, 0xa6, 0xa6, 0x1b, 0x4a, 0x16, 0x53, 0xfc,
	0xdd, 0x31, 0x42, 0x50, 0x87, 0x10, 0xba, 0x02, 0x8d, 0x50, 0x32, 0x2e, 0x2d, 0xd6, 0x0f, 0xa7,
	0x8c, 0xc2, 0x24, 0x8e, 0x36, 0x61, 0x39, 0x94, 0x74, 0x97, 0xf1, 0xa1, 0xda, 0x1c, 0x50, 0x22,
	0x59, 0xd6, 0xbf, 0x37, 0x54, 0x2c, 0xa3, 0x4a, 0x19, 0xf3, 0x57, 0x75, 0xe3, 0xbe, 0x2c, 0xa6,
	0x90, 0xd0, 0x3a, 0x34, 0x4f, 0x14, 0x7f, 0x72, 0x8c, 0xb8, 0x19, 0x9f, 0x24, 0xba, 0x05, 0x5e,
	0xd7, 0x04, 0xbe, 0x08, 0x9b, 0xc2, 0x3f, 0xdd, 0xd6, 0x6c, 0x7b, 0xe1, 0xda, 0x7f, 0x6b, 0x44,
	0xb0, 0x35, 0xbb, 0x15, 0x79, 0xa9, 0x4d, 0x44, 0xab, 0x50, 0x2f, 0xe3, 0xab, 0xf0, 0xfe, 0xc1,
	0x8c, 0x51, 0xb9, 0x46, 0x55, 0xc2, 0x51, 0xbd, 0xcc, 0xb1, 0xca, 0x5d, 0xec, 0x24, 0x2a, 0xfc,
	0xc6, 0xb7, 0x5c, 0xec, 0x56, 0xe4, 0xd9, 0xc9, 0x54, 0xc1, 0xeb, 0x19, 0x40, 0x5d, 0xa2, 0xd4,
	0xa9, 0xa3, 0x79, 0x01, 0xea, 0x21, 0x57, 0x11, 0x7d, 0xb2, 0x95, 0xe0, 0x0f, 0xc5, 0x75, 0xd7,
	0x45, 0x09, 0x4c, 0xc9, 0xed, 0x69, 0x62, 0xb9, 0x01, 0x5e, 0x9e, 0xae, 0xf1, 0x51, 0x14, 0xfe,
	0xe6, 0x98, 0x2d, 0xfe, 0x2f, 0xb6, 0x9e, 0x38, 0x61, 0xe4, 0x71, 0x9b, 0x8a, 0xee, 0x40, 0x63,
	0x5c, 0x3c, 0x60, 0x4a, 0x73, 0x39, 0xc2, 0x5f, 0xa7, 0xa8, 0x0f, 0xdf, 0xa6, 0x92, 0x8c, 0x56,
	0xf2, 0x47, 0xe0, 0x31, 0x8d, 0x75, 0x44, 0x89, 0xe2, 0x19, 0xfe, 0x55, 0x3c, 0x15, 0xae, 0xb4,
	0xc0, 0x3c, 0xc4, 0x3d, 0xba, 0xa7, 0xf1, 0x46, 0x11, 0x62, 0x4d, 0xf7, 0x74, 0x10, 0x1f, 0xfd,
	0xcf, 0xe4, 0x97, 0x30, 0xa4, 0xea, 0xef, 0xdf, 0x5e, 0xf0, 0xa5, 0x02, 0x4b, 0x63, 0x97, 0x2e,
	0x61, 0x99, 0xa6, 0x19, 0xc9, 0x62, 0x7a, 0x46, 0xbf, 0x15, 0x70, 0x43, 0xae, 0xcc, 0x67, 0x31,
	0xda, 0xf7, 0x05, 0xc1, 0x15, 0x16, 0x98, 0xbf, 0x86, 0x21, 0x57, 0xc6, 0xb4, 0x13, 0xe7, 0xfe,
	0xf8, 0x63, 0x41, 0xf3, 0xc5, 0x04, 0x3c, 0xe5, 0xdb, 0xff, 0xe1, 0xb9, 0x09, 0x3e, 0x57, 0xe0,
	0xfc, 0x89, 0x5b, 0x9d, 0x25, 0x82, 0xff, 0x78, 0xa9, 0x9d, 0xaa, 0xf9, 0x61, 0x5b, 0xff, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xd2, 0xee, 0x28, 0xfc, 0xfe, 0x06, 0x00, 0x00,
}
