// Code generated by protoc-gen-go. DO NOT EDIT.
// source: balance.proto

package xmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountStatusReportRequest struct {
	MsgType                string   `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"msgType,omitempty"`
	Account                uint64   `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"account,omitempty"`
	AccountStatusRequestId string   `protobuf:"bytes,42513,opt,name=AccountStatusRequestId,json=accountStatusRequestId,proto3" json:"accountStatusRequestId,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *AccountStatusReportRequest) Reset()         { *m = AccountStatusReportRequest{} }
func (m *AccountStatusReportRequest) String() string { return proto.CompactTextString(m) }
func (*AccountStatusReportRequest) ProtoMessage()    {}
func (*AccountStatusReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{0}
}

func (m *AccountStatusReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountStatusReportRequest.Unmarshal(m, b)
}
func (m *AccountStatusReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountStatusReportRequest.Marshal(b, m, deterministic)
}
func (m *AccountStatusReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStatusReportRequest.Merge(m, src)
}
func (m *AccountStatusReportRequest) XXX_Size() int {
	return xxx_messageInfo_AccountStatusReportRequest.Size(m)
}
func (m *AccountStatusReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStatusReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStatusReportRequest proto.InternalMessageInfo

func (m *AccountStatusReportRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *AccountStatusReportRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *AccountStatusReportRequest) GetAccountStatusRequestId() string {
	if m != nil {
		return m.AccountStatusRequestId
	}
	return ""
}

type Position struct {
	Currency             string   `protobuf:"bytes,15,opt,name=Currency,json=currency,proto3" json:"currency,omitempty"`
	AvgPx                string   `protobuf:"bytes,6,opt,name=AvgPx,json=avgPx,proto3" json:"avgPx,omitempty"`
	PositionId           uint64   `protobuf:"varint,1618,opt,name=PositionId,json=positionId,proto3" json:"positionId,omitempty"`
	PositionOpenTime     int64    `protobuf:"varint,1805,opt,name=PositionOpenTime,json=positionOpenTime,proto3" json:"positionOpenTime,omitempty"`
	RealizedPL           string   `protobuf:"bytes,1806,opt,name=RealizedPL,json=realizedPL,proto3" json:"realizedPL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Position) GetAvgPx() string {
	if m != nil {
		return m.AvgPx
	}
	return ""
}

func (m *Position) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *Position) GetPositionOpenTime() int64 {
	if m != nil {
		return m.PositionOpenTime
	}
	return 0
}

func (m *Position) GetRealizedPL() string {
	if m != nil {
		return m.RealizedPL
	}
	return ""
}

type Balance struct {
	Account              uint64      `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"account,omitempty"`
	Currency             string      `protobuf:"bytes,15,opt,name=Currency,json=currency,proto3" json:"currency,omitempty"`
	LastUpdateTime       int64       `protobuf:"varint,779,opt,name=LastUpdateTime,json=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
	Available            string      `protobuf:"bytes,1801,opt,name=Available,json=available,proto3" json:"available,omitempty"`
	OnHold               string      `protobuf:"bytes,1802,opt,name=OnHold,json=onHold,proto3" json:"onHold,omitempty"`
	Settled              string      `protobuf:"bytes,1803,opt,name=Settled,json=settled,proto3" json:"settled,omitempty"`
	Equity               string      `protobuf:"bytes,1791,opt,name=Equity,json=equity,proto3" json:"equity,omitempty"`
	Bonus                string      `protobuf:"bytes,52313,opt,name=Bonus,json=bonus,proto3" json:"bonus,omitempty"`
	Positions            []*Position `protobuf:"bytes,1804,rep,name=Positions,json=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{2}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Balance) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

func (m *Balance) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *Balance) GetOnHold() string {
	if m != nil {
		return m.OnHold
	}
	return ""
}

func (m *Balance) GetSettled() string {
	if m != nil {
		return m.Settled
	}
	return ""
}

func (m *Balance) GetEquity() string {
	if m != nil {
		return m.Equity
	}
	return ""
}

func (m *Balance) GetBonus() string {
	if m != nil {
		return m.Bonus
	}
	return ""
}

func (m *Balance) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type BalanceIncrementalRefresh struct {
	MsgType                string     `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"msgType,omitempty"`
	Account                uint64     `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"account,omitempty"`
	AccountStatusRequestId string     `protobuf:"bytes,42513,opt,name=AccountStatusRequestId,json=accountStatusRequestId,proto3" json:"accountStatusRequestId,omitempty"`
	LastUpdateTime         int64      `protobuf:"varint,779,opt,name=LastUpdateTime,json=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
	Balances               []*Balance `protobuf:"bytes,1800,rep,name=Balances,json=balances,proto3" json:"balances,omitempty"`
	// reject fields
	RejectReason         string   `protobuf:"bytes,380,opt,name=RejectReason,json=rejectReason,proto3" json:"rejectReason,omitempty"`
	Text                 string   `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceIncrementalRefresh) Reset()         { *m = BalanceIncrementalRefresh{} }
func (m *BalanceIncrementalRefresh) String() string { return proto.CompactTextString(m) }
func (*BalanceIncrementalRefresh) ProtoMessage()    {}
func (*BalanceIncrementalRefresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{3}
}

func (m *BalanceIncrementalRefresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceIncrementalRefresh.Unmarshal(m, b)
}
func (m *BalanceIncrementalRefresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceIncrementalRefresh.Marshal(b, m, deterministic)
}
func (m *BalanceIncrementalRefresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceIncrementalRefresh.Merge(m, src)
}
func (m *BalanceIncrementalRefresh) XXX_Size() int {
	return xxx_messageInfo_BalanceIncrementalRefresh.Size(m)
}
func (m *BalanceIncrementalRefresh) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceIncrementalRefresh.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceIncrementalRefresh proto.InternalMessageInfo

func (m *BalanceIncrementalRefresh) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *BalanceIncrementalRefresh) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *BalanceIncrementalRefresh) GetAccountStatusRequestId() string {
	if m != nil {
		return m.AccountStatusRequestId
	}
	return ""
}

func (m *BalanceIncrementalRefresh) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

func (m *BalanceIncrementalRefresh) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *BalanceIncrementalRefresh) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

func (m *BalanceIncrementalRefresh) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type BalanceSnapshotRefresh struct {
	MsgType                string     `protobuf:"bytes,35,opt,name=MsgType,json=msgType,proto3" json:"msgType,omitempty"`
	Account                uint64     `protobuf:"varint,1,opt,name=Account,json=account,proto3" json:"account,omitempty"`
	AccountStatusRequestId string     `protobuf:"bytes,42513,opt,name=AccountStatusRequestId,json=accountStatusRequestId,proto3" json:"accountStatusRequestId,omitempty"`
	LastUpdateTime         int64      `protobuf:"varint,779,opt,name=LastUpdateTime,json=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
	Balances               []*Balance `protobuf:"bytes,1800,rep,name=Balances,json=balances,proto3" json:"balances,omitempty"`
	// reject fields
	RejectReason         string   `protobuf:"bytes,380,opt,name=RejectReason,json=rejectReason,proto3" json:"rejectReason,omitempty"`
	Text                 string   `protobuf:"bytes,58,opt,name=Text,json=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceSnapshotRefresh) Reset()         { *m = BalanceSnapshotRefresh{} }
func (m *BalanceSnapshotRefresh) String() string { return proto.CompactTextString(m) }
func (*BalanceSnapshotRefresh) ProtoMessage()    {}
func (*BalanceSnapshotRefresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{4}
}

func (m *BalanceSnapshotRefresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceSnapshotRefresh.Unmarshal(m, b)
}
func (m *BalanceSnapshotRefresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceSnapshotRefresh.Marshal(b, m, deterministic)
}
func (m *BalanceSnapshotRefresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceSnapshotRefresh.Merge(m, src)
}
func (m *BalanceSnapshotRefresh) XXX_Size() int {
	return xxx_messageInfo_BalanceSnapshotRefresh.Size(m)
}
func (m *BalanceSnapshotRefresh) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceSnapshotRefresh.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceSnapshotRefresh proto.InternalMessageInfo

func (m *BalanceSnapshotRefresh) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *BalanceSnapshotRefresh) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *BalanceSnapshotRefresh) GetAccountStatusRequestId() string {
	if m != nil {
		return m.AccountStatusRequestId
	}
	return ""
}

func (m *BalanceSnapshotRefresh) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

func (m *BalanceSnapshotRefresh) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *BalanceSnapshotRefresh) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

func (m *BalanceSnapshotRefresh) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountStatusReportRequest)(nil), "xmsg.AccountStatusReportRequest")
	proto.RegisterType((*Position)(nil), "xmsg.Position")
	proto.RegisterType((*Balance)(nil), "xmsg.Balance")
	proto.RegisterType((*BalanceIncrementalRefresh)(nil), "xmsg.BalanceIncrementalRefresh")
	proto.RegisterType((*BalanceSnapshotRefresh)(nil), "xmsg.BalanceSnapshotRefresh")
}

func init() { proto.RegisterFile("balance.proto", fileDescriptor_ee25a00b628521b1) }

var fileDescriptor_ee25a00b628521b1 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0x4f, 0x8b, 0xd3, 0x40,
	0x1c, 0x25, 0xfd, 0x97, 0xe4, 0x67, 0x1b, 0x97, 0x41, 0xea, 0xec, 0x82, 0x58, 0xb2, 0x07, 0x8b,
	0x62, 0x0f, 0x7a, 0x11, 0x6f, 0x5d, 0x11, 0x2c, 0xac, 0x6c, 0x99, 0xd6, 0x0f, 0x30, 0x4d, 0x7e,
	0x76, 0x23, 0xe9, 0x4c, 0x36, 0x33, 0x59, 0x5a, 0x3f, 0x81, 0xee, 0xaa, 0x20, 0x08, 0x0a, 0x7e,
	0x04, 0xbf, 0x8a, 0x27, 0x6f, 0x7e, 0x17, 0x41, 0xc9, 0x4c, 0xb2, 0xe8, 0x22, 0x8b, 0x27, 0x4f,
	0x7b, 0x7c, 0xef, 0xe5, 0xbd, 0xbc, 0x79, 0x4c, 0x02, 0xbd, 0x05, 0x4f, 0xb9, 0x88, 0x70, 0x94,
	0xe5, 0x52, 0x4b, 0xd2, 0x5a, 0xaf, 0xd4, 0x32, 0x3c, 0x71, 0x60, 0x67, 0x1c, 0x45, 0xb2, 0x10,
	0x7a, 0xa6, 0xb9, 0x2e, 0x14, 0xc3, 0x4c, 0xe6, 0x9a, 0xe1, 0x51, 0x81, 0x4a, 0x13, 0x0a, 0xee,
	0x53, 0xb5, 0x9c, 0x6f, 0x32, 0xa4, 0xbb, 0x03, 0x67, 0xe8, 0x33, 0x77, 0x65, 0x61, 0xa9, 0x54,
	0x3e, 0xea, 0x0c, 0x9c, 0x61, 0x8b, 0xb9, 0xdc, 0x42, 0xf2, 0x00, 0xfa, 0xe7, 0x12, 0x4d, 0xd6,
	0x24, 0xa6, 0xef, 0xbf, 0x36, 0x4c, 0x48, 0x9f, 0xff, 0x55, 0x0f, 0xbf, 0x38, 0xe0, 0x4d, 0xa5,
	0x4a, 0x74, 0x22, 0x05, 0xd9, 0x01, 0xef, 0x51, 0x91, 0xe7, 0x28, 0xa2, 0x0d, 0xbd, 0x6a, 0x6c,
	0x5e, 0x54, 0x61, 0x72, 0x0d, 0xda, 0xe3, 0xe3, 0xe5, 0x74, 0x4d, 0x3b, 0x46, 0x68, 0xf3, 0x12,
	0x90, 0x9b, 0x00, 0xb5, 0x7b, 0x12, 0xd3, 0x6f, 0x5d, 0x53, 0x0b, 0xb2, 0x33, 0x8a, 0xdc, 0x81,
	0xad, 0xfa, 0x81, 0x83, 0x0c, 0xc5, 0x3c, 0x59, 0x21, 0x7d, 0x1b, 0x0c, 0x9c, 0x61, 0x93, 0x6d,
	0x65, 0xe7, 0x84, 0x32, 0x8d, 0x21, 0x4f, 0x93, 0x97, 0x18, 0x4f, 0xf7, 0xe9, 0xbb, 0xc0, 0xbc,
	0x09, 0xf2, 0x33, 0x2a, 0xfc, 0xdc, 0x00, 0x77, 0xcf, 0x4e, 0x7a, 0xc1, 0x1a, 0x17, 0x1d, 0xe3,
	0x16, 0x04, 0xfb, 0x5c, 0xe9, 0x67, 0x59, 0xcc, 0x35, 0x9a, 0x36, 0xa7, 0x1d, 0xd3, 0x26, 0x48,
	0xff, 0xa0, 0xc9, 0x0d, 0xf0, 0xc7, 0xc7, 0x3c, 0x49, 0xf9, 0x22, 0x45, 0xfa, 0xda, 0x56, 0xf1,
	0x79, 0xcd, 0x90, 0xeb, 0xd0, 0x39, 0x10, 0x4f, 0x64, 0x1a, 0xd3, 0x13, 0xab, 0x75, 0xa4, 0x81,
	0x64, 0x1b, 0xdc, 0x19, 0x6a, 0x9d, 0x62, 0x4c, 0x4f, 0xad, 0xe2, 0x2a, 0x8b, 0x4b, 0xcf, 0xe3,
	0xa3, 0x22, 0xd1, 0x1b, 0xfa, 0xb3, 0x67, 0x3d, 0x68, 0x20, 0xe9, 0x43, 0x7b, 0x4f, 0x8a, 0x42,
	0xd1, 0xef, 0x9f, 0x9a, 0x76, 0xdd, 0x45, 0x09, 0xc9, 0x5d, 0xf0, 0xeb, 0xf1, 0x14, 0x7d, 0x13,
	0x0c, 0x9a, 0xc3, 0x2b, 0xf7, 0x82, 0x51, 0x79, 0x89, 0x46, 0x35, 0xcf, 0xfc, 0x7a, 0x45, 0x15,
	0x7e, 0x6c, 0xc0, 0x76, 0xb5, 0xce, 0x44, 0x44, 0x39, 0xae, 0x50, 0x68, 0x9e, 0x32, 0x7c, 0x9e,
	0xa3, 0x3a, 0xfc, 0xbf, 0xf7, 0xea, 0xdf, 0x77, 0xbe, 0x0d, 0x5e, 0xd5, 0x59, 0xd1, 0x57, 0xf6,
	0x88, 0x3d, 0x7b, 0xc4, 0x8a, 0x66, 0x5e, 0xf5, 0x11, 0x29, 0xb2, 0x0b, 0x5d, 0x86, 0x2f, 0x30,
	0xd2, 0x0c, 0xb9, 0x92, 0x82, 0xfe, 0xb0, 0x1d, 0xba, 0xf9, 0x6f, 0x24, 0x21, 0xd0, 0x9a, 0xe3,
	0x5a, 0xd3, 0x87, 0x46, 0x6b, 0x69, 0x5c, 0xeb, 0xf0, 0x43, 0x03, 0xfa, 0x55, 0xdc, 0x4c, 0xf0,
	0x4c, 0x1d, 0x4a, 0x7d, 0x39, 0x8b, 0x5e, 0x74, 0xcc, 0x6f, 0xe9, 0xfe, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0x19, 0xc1, 0x39, 0xa7, 0x04, 0x00, 0x00,
}
