// Code generated by protoc-gen-go. DO NOT EDIT.
// source: market.proto

package xmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MDEntry struct {
	Symbol               string   `protobuf:"bytes,55,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	MDUpdateAction       string   `protobuf:"bytes,279,opt,name=MDUpdateAction,proto3" json:"MDUpdateAction,omitempty"`
	MDEntryType          string   `protobuf:"bytes,269,opt,name=MDEntryType,proto3" json:"MDEntryType,omitempty"`
	MDEntryPx            string   `protobuf:"bytes,270,opt,name=MDEntryPx,proto3" json:"MDEntryPx,omitempty"`
	MDEntrySize          string   `protobuf:"bytes,271,opt,name=MDEntrySize,proto3" json:"MDEntrySize,omitempty"`
	NumberOfOrders       uint32   `protobuf:"varint,346,opt,name=NumberOfOrders,proto3" json:"NumberOfOrders,omitempty"`
	TransactTime         int64    `protobuf:"varint,60,opt,name=TransactTime,proto3" json:"TransactTime,omitempty"`
	TradeId              string   `protobuf:"bytes,1003,opt,name=TradeId,proto3" json:"TradeId,omitempty"`
	AggressorSide        string   `protobuf:"bytes,1501,opt,name=AggressorSide,proto3" json:"AggressorSide,omitempty"`
	FirstPx              string   `protobuf:"bytes,1025,opt,name=FirstPx,proto3" json:"FirstPx,omitempty"`
	LastPx               string   `protobuf:"bytes,31,opt,name=LastPx,proto3" json:"LastPx,omitempty"`
	HighPx               string   `protobuf:"bytes,332,opt,name=HighPx,proto3" json:"HighPx,omitempty"`
	LowPx                string   `protobuf:"bytes,333,opt,name=LowPx,proto3" json:"LowPx,omitempty"`
	BuyVolume            string   `protobuf:"bytes,330,opt,name=BuyVolume,proto3" json:"BuyVolume,omitempty"`
	SellVolume           string   `protobuf:"bytes,331,opt,name=SellVolume,proto3" json:"SellVolume,omitempty"`
	Bid                  string   `protobuf:"bytes,1502,opt,name=Bid,proto3" json:"Bid,omitempty"`
	Ask                  string   `protobuf:"bytes,1503,opt,name=Ask,proto3" json:"Ask,omitempty"`
	LowRangePx           string   `protobuf:"bytes,35601,opt,name=LowRangePx,proto3" json:"LowRangePx,omitempty"`
	HighRangePx          string   `protobuf:"bytes,35602,opt,name=HighRangePx,proto3" json:"HighRangePx,omitempty"`
	LowLimitPx           string   `protobuf:"bytes,35603,opt,name=LowLimitPx,proto3" json:"LowLimitPx,omitempty"`
	HighLimitPx          string   `protobuf:"bytes,35604,opt,name=HighLimitPx,proto3" json:"HighLimitPx,omitempty"`
	ClearingPx           string   `protobuf:"bytes,35605,opt,name=ClearingPx,proto3" json:"ClearingPx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MDEntry) Reset()         { *m = MDEntry{} }
func (m *MDEntry) String() string { return proto.CompactTextString(m) }
func (*MDEntry) ProtoMessage()    {}
func (*MDEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{0}
}

func (m *MDEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MDEntry.Unmarshal(m, b)
}
func (m *MDEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MDEntry.Marshal(b, m, deterministic)
}
func (m *MDEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MDEntry.Merge(m, src)
}
func (m *MDEntry) XXX_Size() int {
	return xxx_messageInfo_MDEntry.Size(m)
}
func (m *MDEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MDEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MDEntry proto.InternalMessageInfo

func (m *MDEntry) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MDEntry) GetMDUpdateAction() string {
	if m != nil {
		return m.MDUpdateAction
	}
	return ""
}

func (m *MDEntry) GetMDEntryType() string {
	if m != nil {
		return m.MDEntryType
	}
	return ""
}

func (m *MDEntry) GetMDEntryPx() string {
	if m != nil {
		return m.MDEntryPx
	}
	return ""
}

func (m *MDEntry) GetMDEntrySize() string {
	if m != nil {
		return m.MDEntrySize
	}
	return ""
}

func (m *MDEntry) GetNumberOfOrders() uint32 {
	if m != nil {
		return m.NumberOfOrders
	}
	return 0
}

func (m *MDEntry) GetTransactTime() int64 {
	if m != nil {
		return m.TransactTime
	}
	return 0
}

func (m *MDEntry) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *MDEntry) GetAggressorSide() string {
	if m != nil {
		return m.AggressorSide
	}
	return ""
}

func (m *MDEntry) GetFirstPx() string {
	if m != nil {
		return m.FirstPx
	}
	return ""
}

func (m *MDEntry) GetLastPx() string {
	if m != nil {
		return m.LastPx
	}
	return ""
}

func (m *MDEntry) GetHighPx() string {
	if m != nil {
		return m.HighPx
	}
	return ""
}

func (m *MDEntry) GetLowPx() string {
	if m != nil {
		return m.LowPx
	}
	return ""
}

func (m *MDEntry) GetBuyVolume() string {
	if m != nil {
		return m.BuyVolume
	}
	return ""
}

func (m *MDEntry) GetSellVolume() string {
	if m != nil {
		return m.SellVolume
	}
	return ""
}

func (m *MDEntry) GetBid() string {
	if m != nil {
		return m.Bid
	}
	return ""
}

func (m *MDEntry) GetAsk() string {
	if m != nil {
		return m.Ask
	}
	return ""
}

func (m *MDEntry) GetLowRangePx() string {
	if m != nil {
		return m.LowRangePx
	}
	return ""
}

func (m *MDEntry) GetHighRangePx() string {
	if m != nil {
		return m.HighRangePx
	}
	return ""
}

func (m *MDEntry) GetLowLimitPx() string {
	if m != nil {
		return m.LowLimitPx
	}
	return ""
}

func (m *MDEntry) GetHighLimitPx() string {
	if m != nil {
		return m.HighLimitPx
	}
	return ""
}

func (m *MDEntry) GetClearingPx() string {
	if m != nil {
		return m.ClearingPx
	}
	return ""
}

type MarketDataRefresh struct {
	MsgType              string     `protobuf:"bytes,35,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MDStreamId           string     `protobuf:"bytes,1500,opt,name=MDStreamId,proto3" json:"MDStreamId,omitempty"`
	LastUpdateTime       int64      `protobuf:"varint,779,opt,name=LastUpdateTime,proto3" json:"LastUpdateTime,omitempty"`
	MDBookType           string     `protobuf:"bytes,1021,opt,name=MDBookType,proto3" json:"MDBookType,omitempty"`
	Symbol               string     `protobuf:"bytes,55,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	LowRangePx           string     `protobuf:"bytes,35601,opt,name=LowRangePx,proto3" json:"LowRangePx,omitempty"`
	HighRangePx          string     `protobuf:"bytes,35602,opt,name=HighRangePx,proto3" json:"HighRangePx,omitempty"`
	LowLimitPx           string     `protobuf:"bytes,35603,opt,name=LowLimitPx,proto3" json:"LowLimitPx,omitempty"`
	HighLimitPx          string     `protobuf:"bytes,35604,opt,name=HighLimitPx,proto3" json:"HighLimitPx,omitempty"`
	ClearingPx           string     `protobuf:"bytes,35605,opt,name=ClearingPx,proto3" json:"ClearingPx,omitempty"`
	BestBid              string     `protobuf:"bytes,1502,opt,name=BestBid,proto3" json:"BestBid,omitempty"`
	BestAsk              string     `protobuf:"bytes,1503,opt,name=BestAsk,proto3" json:"BestAsk,omitempty"`
	MDEntry              []*MDEntry `protobuf:"bytes,268,rep,name=MDEntry,proto3" json:"MDEntry,omitempty"`
	Ratios               []*MDEntry `protobuf:"bytes,1504,rep,name=Ratios,proto3" json:"Ratios,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MarketDataRefresh) Reset()         { *m = MarketDataRefresh{} }
func (m *MarketDataRefresh) String() string { return proto.CompactTextString(m) }
func (*MarketDataRefresh) ProtoMessage()    {}
func (*MarketDataRefresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{1}
}

func (m *MarketDataRefresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDataRefresh.Unmarshal(m, b)
}
func (m *MarketDataRefresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDataRefresh.Marshal(b, m, deterministic)
}
func (m *MarketDataRefresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDataRefresh.Merge(m, src)
}
func (m *MarketDataRefresh) XXX_Size() int {
	return xxx_messageInfo_MarketDataRefresh.Size(m)
}
func (m *MarketDataRefresh) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDataRefresh.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDataRefresh proto.InternalMessageInfo

func (m *MarketDataRefresh) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MarketDataRefresh) GetMDStreamId() string {
	if m != nil {
		return m.MDStreamId
	}
	return ""
}

func (m *MarketDataRefresh) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

func (m *MarketDataRefresh) GetMDBookType() string {
	if m != nil {
		return m.MDBookType
	}
	return ""
}

func (m *MarketDataRefresh) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MarketDataRefresh) GetLowRangePx() string {
	if m != nil {
		return m.LowRangePx
	}
	return ""
}

func (m *MarketDataRefresh) GetHighRangePx() string {
	if m != nil {
		return m.HighRangePx
	}
	return ""
}

func (m *MarketDataRefresh) GetLowLimitPx() string {
	if m != nil {
		return m.LowLimitPx
	}
	return ""
}

func (m *MarketDataRefresh) GetHighLimitPx() string {
	if m != nil {
		return m.HighLimitPx
	}
	return ""
}

func (m *MarketDataRefresh) GetClearingPx() string {
	if m != nil {
		return m.ClearingPx
	}
	return ""
}

func (m *MarketDataRefresh) GetBestBid() string {
	if m != nil {
		return m.BestBid
	}
	return ""
}

func (m *MarketDataRefresh) GetBestAsk() string {
	if m != nil {
		return m.BestAsk
	}
	return ""
}

func (m *MarketDataRefresh) GetMDEntry() []*MDEntry {
	if m != nil {
		return m.MDEntry
	}
	return nil
}

func (m *MarketDataRefresh) GetRatios() []*MDEntry {
	if m != nil {
		return m.Ratios
	}
	return nil
}

type MarketDataRequest struct {
	MsgType                 string   `protobuf:"bytes,35,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MDStreamId              string   `protobuf:"bytes,1500,opt,name=MDStreamId,proto3" json:"MDStreamId,omitempty"`
	SubscriptionRequestType string   `protobuf:"bytes,263,opt,name=SubscriptionRequestType,proto3" json:"SubscriptionRequestType,omitempty"`
	ThrottleType            string   `protobuf:"bytes,1612,opt,name=ThrottleType,proto3" json:"ThrottleType,omitempty"`
	ThrottleTimeInterval    int64    `protobuf:"varint,1614,opt,name=ThrottleTimeInterval,proto3" json:"ThrottleTimeInterval,omitempty"`
	ThrottleTimeUnit        string   `protobuf:"bytes,1615,opt,name=ThrottleTimeUnit,proto3" json:"ThrottleTimeUnit,omitempty"`
	AggregatedBook          int64    `protobuf:"varint,266,opt,name=AggregatedBook,proto3" json:"AggregatedBook,omitempty"`
	MarketDepth             int64    `protobuf:"varint,264,opt,name=MarketDepth,proto3" json:"MarketDepth,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *MarketDataRequest) Reset()         { *m = MarketDataRequest{} }
func (m *MarketDataRequest) String() string { return proto.CompactTextString(m) }
func (*MarketDataRequest) ProtoMessage()    {}
func (*MarketDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{2}
}

func (m *MarketDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDataRequest.Unmarshal(m, b)
}
func (m *MarketDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDataRequest.Marshal(b, m, deterministic)
}
func (m *MarketDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDataRequest.Merge(m, src)
}
func (m *MarketDataRequest) XXX_Size() int {
	return xxx_messageInfo_MarketDataRequest.Size(m)
}
func (m *MarketDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDataRequest proto.InternalMessageInfo

func (m *MarketDataRequest) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MarketDataRequest) GetMDStreamId() string {
	if m != nil {
		return m.MDStreamId
	}
	return ""
}

func (m *MarketDataRequest) GetSubscriptionRequestType() string {
	if m != nil {
		return m.SubscriptionRequestType
	}
	return ""
}

func (m *MarketDataRequest) GetThrottleType() string {
	if m != nil {
		return m.ThrottleType
	}
	return ""
}

func (m *MarketDataRequest) GetThrottleTimeInterval() int64 {
	if m != nil {
		return m.ThrottleTimeInterval
	}
	return 0
}

func (m *MarketDataRequest) GetThrottleTimeUnit() string {
	if m != nil {
		return m.ThrottleTimeUnit
	}
	return ""
}

func (m *MarketDataRequest) GetAggregatedBook() int64 {
	if m != nil {
		return m.AggregatedBook
	}
	return 0
}

func (m *MarketDataRequest) GetMarketDepth() int64 {
	if m != nil {
		return m.MarketDepth
	}
	return 0
}

type MarketDataRequestReject struct {
	MsgType              string   `protobuf:"bytes,35,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MDStreamId           string   `protobuf:"bytes,1500,opt,name=MDStreamId,proto3" json:"MDStreamId,omitempty"`
	RejectText           string   `protobuf:"bytes,1328,opt,name=RejectText,proto3" json:"RejectText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketDataRequestReject) Reset()         { *m = MarketDataRequestReject{} }
func (m *MarketDataRequestReject) String() string { return proto.CompactTextString(m) }
func (*MarketDataRequestReject) ProtoMessage()    {}
func (*MarketDataRequestReject) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{3}
}

func (m *MarketDataRequestReject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDataRequestReject.Unmarshal(m, b)
}
func (m *MarketDataRequestReject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDataRequestReject.Marshal(b, m, deterministic)
}
func (m *MarketDataRequestReject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDataRequestReject.Merge(m, src)
}
func (m *MarketDataRequestReject) XXX_Size() int {
	return xxx_messageInfo_MarketDataRequestReject.Size(m)
}
func (m *MarketDataRequestReject) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDataRequestReject.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDataRequestReject proto.InternalMessageInfo

func (m *MarketDataRequestReject) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MarketDataRequestReject) GetMDStreamId() string {
	if m != nil {
		return m.MDStreamId
	}
	return ""
}

func (m *MarketDataRequestReject) GetRejectText() string {
	if m != nil {
		return m.RejectText
	}
	return ""
}

func init() {
	proto.RegisterType((*MDEntry)(nil), "xmsg.MDEntry")
	proto.RegisterType((*MarketDataRefresh)(nil), "xmsg.MarketDataRefresh")
	proto.RegisterType((*MarketDataRequest)(nil), "xmsg.MarketDataRequest")
	proto.RegisterType((*MarketDataRequestReject)(nil), "xmsg.MarketDataRequestReject")
}

func init() { proto.RegisterFile("market.proto", fileDescriptor_3f90997f23a2c3f8) }

var fileDescriptor_3f90997f23a2c3f8 = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x95, 0xbb, 0x6e, 0x13, 0x4f,
	0x14, 0xc6, 0x15, 0xfb, 0x1f, 0xfb, 0x9f, 0x63, 0x07, 0x91, 0x11, 0x90, 0xa1, 0x40, 0x31, 0x8e,
	0x00, 0x4b, 0x48, 0x29, 0x48, 0x81, 0x90, 0x68, 0x6c, 0x0c, 0x22, 0x92, 0x4d, 0xac, 0xb5, 0x43,
	0x3f, 0xf6, 0x4e, 0xd6, 0x83, 0xbd, 0xbb, 0x66, 0x66, 0x4c, 0xd6, 0x74, 0x54, 0x20, 0xae, 0xe2,
	0xfe, 0x1a, 0x34, 0xbc, 0x04, 0x04, 0xe8, 0x51, 0xb8, 0x54, 0x34, 0x3c, 0x03, 0x12, 0x9a, 0xcb,
	0xda, 0xeb, 0x5c, 0xaa, 0x54, 0x74, 0x39, 0xbf, 0xf3, 0xe9, 0xdb, 0x99, 0x33, 0x5f, 0x8e, 0x21,
	0xef, 0x13, 0xde, 0xa3, 0x72, 0x65, 0xc0, 0x43, 0x19, 0xa2, 0xff, 0x22, 0x5f, 0x78, 0xc5, 0xf7,
	0xb3, 0x90, 0xad, 0x57, 0xaf, 0x06, 0x92, 0x8f, 0xd0, 0x09, 0xc8, 0x34, 0x47, 0x7e, 0x3b, 0xec,
	0xe3, 0x8b, 0x85, 0x99, 0xd2, 0x9c, 0x63, 0x2b, 0x74, 0x0e, 0x8e, 0xd4, 0xab, 0x1b, 0x03, 0x97,
	0x48, 0x5a, 0xee, 0x48, 0x16, 0x06, 0xf8, 0x6d, 0x4a, 0x0b, 0x76, 0x61, 0x74, 0x1a, 0x72, 0xd6,
	0xab, 0x35, 0x1a, 0x50, 0xfc, 0xc4, 0xa8, 0x92, 0x0c, 0x9d, 0x82, 0x39, 0x5b, 0x36, 0x22, 0xfc,
	0xd4, 0x08, 0x26, 0x24, 0xe1, 0xd0, 0x64, 0x77, 0x29, 0x7e, 0x36, 0xed, 0xa0, 0x98, 0x3a, 0xcd,
	0x8d, 0xa1, 0xdf, 0xa6, 0x7c, 0x7d, 0x73, 0x9d, 0xbb, 0x94, 0x0b, 0xfc, 0x55, 0xa9, 0xe6, 0x9d,
	0x5d, 0x18, 0x15, 0x21, 0xdf, 0xe2, 0x24, 0x10, 0xa4, 0x23, 0x5b, 0xcc, 0xa7, 0xf8, 0x72, 0x61,
	0xa6, 0x94, 0x76, 0xa6, 0x18, 0x3a, 0x09, 0xd9, 0x16, 0x27, 0x2e, 0x5d, 0x73, 0xf1, 0xef, 0xac,
	0xfe, 0x56, 0x5c, 0xa3, 0x33, 0x30, 0x5f, 0xf6, 0x3c, 0x4e, 0x85, 0x08, 0x79, 0x93, 0xb9, 0x14,
	0x7f, 0xcb, 0x69, 0xc1, 0x34, 0x55, 0x0e, 0xd7, 0x18, 0x17, 0xb2, 0x11, 0xe1, 0x7b, 0xff, 0x1b,
	0x07, 0x5b, 0xab, 0x79, 0xd6, 0x88, 0xee, 0x2c, 0x99, 0x79, 0x9a, 0x0a, 0x2d, 0x42, 0xe6, 0x3a,
	0xf3, 0xba, 0x8d, 0x08, 0x6f, 0x9b, 0xfb, 0xd9, 0x12, 0x1d, 0x87, 0xd9, 0x5a, 0xb8, 0xd5, 0x88,
	0xf0, 0x27, 0xc3, 0x4d, 0xa5, 0x66, 0x56, 0x19, 0x8e, 0x6e, 0x86, 0xfd, 0xa1, 0x4f, 0xf1, 0x07,
	0x3b, 0xb3, 0x31, 0x41, 0x4b, 0x00, 0x4d, 0xda, 0xef, 0xdb, 0xfe, 0x47, 0xd3, 0x4f, 0x20, 0xb4,
	0x00, 0xe9, 0x0a, 0x73, 0xf1, 0x77, 0x73, 0x7e, 0xf5, 0xb7, 0x42, 0x65, 0xd1, 0xc3, 0x3f, 0x2c,
	0x2a, 0x8b, 0x1e, 0x2a, 0x00, 0xd4, 0xc2, 0x2d, 0x87, 0x04, 0x1e, 0x6d, 0x44, 0xf8, 0xf9, 0x1b,
	0xeb, 0x33, 0x61, 0xa8, 0x08, 0x39, 0x75, 0xd0, 0x58, 0xf2, 0xc2, 0x4a, 0x92, 0xd0, 0xba, 0xd4,
	0x98, 0xcf, 0xd4, 0xbd, 0x5f, 0x26, 0x5c, 0x2c, 0x8b, 0x5d, 0x62, 0xc9, 0xab, 0xa4, 0x4b, 0xac,
	0x29, 0x00, 0x5c, 0xe9, 0x53, 0xc2, 0x59, 0xe0, 0x35, 0x22, 0xfc, 0x3a, 0x76, 0x99, 0xb0, 0xe2,
	0xaf, 0x34, 0x2c, 0xd4, 0x75, 0x9c, 0xab, 0x44, 0x12, 0x87, 0x6e, 0x72, 0x2a, 0xba, 0x08, 0x43,
	0xb6, 0x2e, 0x3c, 0x1d, 0xbe, 0x65, 0xf3, 0x16, 0xb6, 0x54, 0x43, 0xaa, 0x57, 0x9b, 0x92, 0x53,
	0xe2, 0xaf, 0xb9, 0x78, 0xc7, 0xdc, 0x3b, 0x81, 0x54, 0xac, 0xd4, 0xf3, 0x98, 0x3c, 0xeb, 0xbc,
	0x3c, 0xca, 0xe8, 0xc0, 0xec, 0xc2, 0xc6, 0xa9, 0x12, 0x86, 0x3d, 0xfd, 0x99, 0x3f, 0xd9, 0xd8,
	0x29, 0x46, 0x07, 0xfe, 0x1b, 0xfd, 0x53, 0x03, 0x56, 0xb9, 0xae, 0x50, 0x21, 0x13, 0xc1, 0x89,
	0xeb, 0xb8, 0x95, 0x08, 0x50, 0x5c, 0xa3, 0xd2, 0x78, 0x9b, 0xe0, 0xc7, 0xa9, 0x42, 0xba, 0x94,
	0xbb, 0x30, 0xbf, 0xa2, 0xf6, 0xcc, 0x8a, 0xa5, 0xce, 0x78, 0xd9, 0x9c, 0x85, 0x8c, 0x43, 0x24,
	0x0b, 0x05, 0xfe, 0x99, 0xdb, 0x4f, 0x68, 0xbb, 0xc5, 0x9d, 0xd4, 0xf4, 0x43, 0xdf, 0x1e, 0x52,
	0x21, 0x0f, 0xf3, 0xd0, 0x97, 0x60, 0xb1, 0x39, 0x6c, 0x8b, 0x0e, 0x67, 0x03, 0xb5, 0xb4, 0xac,
	0xa3, 0xb6, 0xba, 0x6f, 0xc6, 0x70, 0x50, 0x1f, 0x2d, 0x43, 0xbe, 0xd5, 0xe5, 0xa1, 0x94, 0x7d,
	0xaa, 0xf5, 0xdb, 0x79, 0xad, 0x9f, 0x82, 0x68, 0x15, 0x8e, 0x8d, 0x6b, 0xe6, 0xd3, 0xb5, 0x40,
	0x52, 0x7e, 0x87, 0xf4, 0xf1, 0xe7, 0xbc, 0x8e, 0xd3, 0xbe, 0x4d, 0x74, 0x1e, 0x8e, 0x26, 0xf9,
	0x46, 0xc0, 0x24, 0xfe, 0x62, 0xdc, 0xf7, 0x34, 0x54, 0x54, 0xf5, 0x0e, 0xf2, 0x88, 0xa4, 0xae,
	0x8a, 0x1d, 0x7e, 0x98, 0x32, 0x51, 0x9d, 0xc6, 0x7a, 0x9b, 0x9a, 0xd1, 0xd1, 0x81, 0xec, 0xe2,
	0x07, 0x46, 0x95, 0x64, 0xc5, 0x21, 0x2c, 0xee, 0x99, 0xae, 0x43, 0x6f, 0xd1, 0xce, 0xa1, 0x66,
	0xbc, 0x04, 0x60, 0x4c, 0x5a, 0x34, 0x92, 0xf8, 0x1d, 0x18, 0xc1, 0x04, 0xb5, 0x33, 0xfa, 0x37,
	0x68, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x37, 0xe8, 0x0f, 0x93, 0x06, 0x00, 0x00,
}
